/* We Can 1 · Global Lesson 1 · Ready for We Can! · 25-min 1v1 */
const A='assets/',$=s=>document.querySelector(s);let curAudio=null,cur=0,toastTimer;
function play(src){stopAudio();curAudio=new Audio(A+src);curAudio.play().catch(()=>{});}
function stopAudio(){if(curAudio){curAudio.pause();curAudio.currentTime=0;curAudio=null;}}
function sfx(src){new Audio(A+src).play().catch(()=>{});}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1700);}

const style=document.createElement('style');style.textContent=`
  .row{display:flex;align-items:center;justify-content:center;gap:24px;width:100%}.grid{display:grid;gap:18px;width:100%}
  .big{font-size:44px;font-weight:800;color:#293b59;text-align:center}.sub{font-size:21px;color:#786845;text-align:center;margin-top:8px}
  .pill{border:0;border-radius:18px;padding:16px 24px;font:800 23px inherit;cursor:pointer;background:#fff;color:#293b59;box-shadow:0 5px 0 #dfd2bb}
  .pill:active{transform:translateY(3px);box-shadow:0 2px 0 #dfd2bb}.orange{background:#ff8c42;color:#fff;box-shadow:0 5px 0 #d96f2a}
  .blue{background:#2b6cb0;color:#fff;box-shadow:0 5px 0 #1d4e82}.green{background:#1f9d6c;color:#fff;box-shadow:0 5px 0 #157a52}
  .soft{background:#fff;border:3px solid #e6d7bd;border-radius:22px;padding:18px}.command{min-height:150px;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:10px}
  .command strong{font-size:34px;color:#293b59}.command small{font-size:17px;color:#7b6c50}.selected{outline:6px solid #f6b93b;background:#fff8df!important}
  .good{outline:6px solid #1f9d6c;background:#e9fff6!important}.bad{animation:shake .35s}.tag{display:inline-block;padding:6px 12px;border-radius:14px;background:#e8f1fb;color:#2b6cb0;font-weight:800}
  .teacher{position:absolute;right:18px;bottom:10px;background:#293b59;color:#fff;border-radius:12px;padding:8px 14px;font-size:13px;max-width:430px}
  .step{width:54px;height:54px;border-radius:50%;border:3px solid #e6d7bd;background:#fff;color:#8a6d3b;font-size:20px;font-weight:800;cursor:pointer}.step.done{background:#1f9d6c;color:#fff;border-color:#157a52}
  .grade{padding:12px 18px;border:0;border-radius:14px;color:#fff;font-weight:800;font-size:17px;cursor:pointer}.grade[data-g=A]{background:#1f9d6c}.grade[data-g=B]{background:#f0a52b}.grade[data-g=C]{background:#e85b4f}
  @keyframes shake{25%{transform:translateX(-9px)}75%{transform:translateX(9px)}}
`;document.head.appendChild(style);

let liveTimer=null;const screens=[],host=$('#screens');
function addScreen(objective,html,init){const el=document.createElement('section');el.className='screen';el.innerHTML=html;host.appendChild(el);const api=init?init(el):{};screens.push({objective,el,onEnter:api.onEnter,onLeave:api.onLeave});}
function show(i){i=Math.max(0,Math.min(screens.length-1,i));if(screens[cur]?.onLeave)screens[cur].onLeave();stopAudio();clearInterval(liveTimer);cur=i;screens.forEach((s,k)=>s.el.classList.toggle('active',k===i));$('#objective').textContent='Objective · '+screens[i].objective;$('#page-num').textContent=`${i+1} / ${screens.length}`;$('#progress').style.width=`${(i+1)/screens.length*100}%`;$('#btn-prev').disabled=i===0;$('#btn-next').disabled=i===screens.length-1;document.querySelectorAll('#thumbs button').forEach((b,k)=>b.classList.toggle('cur',k===i));screens[i].onEnter?.();}
function fit(){const z=Math.min(innerWidth/1280,innerHeight/720);$('#stage').style.transform=`scale(${z})`;}addEventListener('resize',fit);
(function(){const w=$('#watermark');for(let y=0;y<5;y++)for(let x=0;x<4;x++){const n=document.createElement('span');n.textContent='khusoosi · خصوصي';n.style.left=(x*340+(y%2)*120)+'px';n.style.top=(y*150+20)+'px';w.appendChild(n);}})();
$('#btn-ar').onclick=()=>{const on=document.body.classList.toggle('ar-on');$('#btn-ar').setAttribute('aria-pressed',String(on));};
$('#btn-prev').onclick=()=>show(cur-1);$('#btn-next').onclick=()=>show(cur+1);$('#btn-thumbs').onclick=()=>$('#thumbs').classList.toggle('open');$('#btn-fs').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>{});
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')show(cur+1);if(e.key==='ArrowLeft')show(cur-1);});
host.addEventListener('click',e=>{const b=e.target.closest('[data-audio]');if(b){play(b.dataset.audio);toast(b.dataset.toast||'Listen');}});

const audio={Look:'a_r_look.wav',Listen:'a_r_listen.wav',Point:'a_r_point.wav',Choose:'a_r_choose.wav','Say it':'a_r_say.wav','Show me':'a_r_show.wav','Open your book':'a_r_open.wav','Take a pencil':'a_r_pencil.wav'};
const commands=Object.keys(audio);const result={baseline:{},check1:[],errors:[],check2:[],band:'Not checked'};
const ar={Look:'انظر',Listen:'استمع',Point:'أشر','Choose':'اختر','Say it':'قلها','Show me':'أرني','Open your book':'افتح كتابك','Take a pencil':'خذ قلمًا'};
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function commandCard(c,extra=''){return `<button class="pill command" data-c="${c}" ${extra}><span class="tag">CLASS WORDS</span><strong>${c}</strong><span class="ar">${ar[c]}</span><small>Tap to hear</small></button>`;}
function bindAudioCards(el){el.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>play(audio[b.dataset.c]));}
function gradeButtons(id){return `<div class="row" id="${id}" style="gap:12px"><button class="grade" data-g="A">A · Independent</button><button class="grade" data-g="B">B · With help</button><button class="grade" data-g="C">C · Not yet</button></div>`;}

addScreen('prepare for class',`<div style="direction:rtl;text-align:center;width:100%"><div class="big">جاهز لدرس We Can؟</div><div class="sub">جهّز الصوت، الكتاب، والقلم</div><div class="grid" style="grid-template-columns:repeat(3,1fr);max-width:950px;margin:34px auto"><div class="soft"><div style="font-size:30px;font-weight:800">الميكروفون</div><p>شغّله وتكلّم بوضوح</p></div><div class="soft"><div style="font-size:30px;font-weight:800">الكتاب</div><p>ضعه أمامك</p></div><div class="soft"><div style="font-size:30px;font-weight:800">القلم</div><p>اجعله قريبًا منك</p></div></div><button class="pill blue" data-audio="a_t_soundcheck.mp3">اختبار الصوت</button></div>`);

addScreen('quick baseline — no teaching',`<div class="row"><img src="${A}sec_teacher.png" class="pic" style="width:350px;height:440px"><div style="max-width:590px"><div class="big" style="text-align:left">Welcome!</div><div class="soft" style="font-size:28px;margin:18px 0">Teacher says: <b>Hello! What’s your name?</b></div><p class="sub" style="text-align:left">Wait 5 seconds. Record only; do not teach yet.</p>${gradeButtons('base-grade')}</div></div><div class="teacher">BASELINE · also note: 3 colors, first sound, 5-second attention.</div>`,el=>{el.querySelectorAll('.grade').forEach(b=>b.onclick=()=>{result.baseline.hello=b.dataset.g;el.querySelectorAll('.grade').forEach(x=>x.classList.toggle('selected',x===b));toast('Baseline saved');});return{};});

addScreen('see the lesson promise',`<div class="row"><img src="${A}textbook_cover.png" class="pic" style="width:280px;max-height:460px;box-shadow:0 10px 28px #0003"><div style="max-width:650px"><div class="big" style="text-align:left">Ready for We Can!</div><div class="sub" style="text-align:left;margin-bottom:22px">Today I can understand class words.</div><div class="soft" style="font-size:26px;line-height:1.8"><b>1.</b> Listen and act<br><b>2.</b> Ask for help<br><b>3.</b> Do a school-book task</div><div class="ar sub" style="text-align:right">أفهم تعليمات الدرس وأطلب المساعدة</div></div></div>`);

addScreen('understand Look and Listen',`<div class="grid" style="grid-template-columns:1fr 1fr;max-width:900px">${commandCard('Look')}${commandCard('Listen')}</div><div class="sub">Teacher: say it → model it → student acts.</div>`,el=>{bindAudioCards(el);return{};});

addScreen('understand Point and Choose',`<div class="grid" style="grid-template-columns:1fr 1fr;max-width:900px">${commandCard('Point')}${commandCard('Choose')}</div><div id="pc-task" class="soft" style="margin-top:22px;font-size:25px">Point to <b style="color:#e85b4f">RED</b>, then choose it: <button class="pill" data-v="blue">BLUE</button> <button class="pill" data-v="red">RED</button></div>`,el=>{bindAudioCards(el);el.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(b.dataset.v==='red'){b.classList.add('good');sfx('sfx_correct.mp3');toast('Yes — choose red!');}else{b.classList.add('bad');sfx('sfx_wrong.mp3');setTimeout(()=>b.classList.remove('bad'),400);}});return{};});

addScreen('understand Say, Show, Open',`<div class="grid" style="grid-template-columns:repeat(3,1fr);max-width:1100px">${commandCard('Say it')}${commandCard('Show me')}${commandCard('Open your book')}</div><div class="sub">Listen. Do the action. Then say <b>Okay.</b></div>`,el=>{bindAudioCards(el);return{};});

addScreen('hear a command without text',`<div class="big">Listen. Which command?</div><button class="speaker" id="sound-only" style="margin:22px"></button><div class="grid" id="sound-options" style="grid-template-columns:repeat(4,1fr);max-width:1080px"></div><div id="sound-score" class="sub">0 / 4</div>`,el=>{let target,score=0;const box=el.querySelector('#sound-options');function next(){target=commands[Math.floor(Math.random()*commands.length)];box.innerHTML=shuffle(commands).slice(0,4).map((c,i)=>i===0||c!==target?`<button class="pill" data-answer="${c}">${c}</button>`:'').join('');if(![...box.children].some(b=>b.dataset.answer===target))box.lastElementChild.dataset.answer=target,box.lastElementChild.textContent=target;shuffle([...box.children]).forEach(b=>box.appendChild(b));box.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.dataset.answer===target){b.classList.add('good');score++;el.querySelector('#sound-score').textContent=`${score} / 4`;sfx('sfx_correct.mp3');setTimeout(next,450);}else{b.classList.add('bad');setTimeout(()=>b.classList.remove('bad'),350);}});play(audio[target]);}el.querySelector('#sound-only').onclick=()=>play(audio[target]);return{onEnter(){score=0;next();}};});

addScreen('connect to the school textbook',`<div class="row"><img src="${A}sec_textbook_intro_2.jpg" class="pic" style="width:480px;height:500px;object-position:left center;border:5px solid #fff;box-shadow:0 8px 22px #0003"><div style="max-width:550px"><div class="big" style="text-align:left">This is your school book.</div><div class="soft" style="font-size:25px;line-height:1.7;margin-top:18px"><b>Listen and point.</b><br>Put your bags away.<br>Take out your pencils.<br>Take out your books.</div><div class="ar sub" style="text-align:right">نفس صفحة كتاب المدرسة، لكننا نفهمها خطوة بخطوة.</div></div></div><div class="teacher">SOURCE · Student Book pp.2–3 (PDF pp.8–9), 1448 edition.</div>`);

addScreen('follow the textbook action',`<div class="big">Teacher gives one command.</div><div class="grid" style="grid-template-columns:repeat(3,1fr);max-width:1040px;margin-top:20px"><button class="soft command" data-act="bag"><img src="${A}sec_action_bag.jpg" class="pic" style="height:230px"><b>Bag away</b></button><button class="soft command" data-act="pencil"><img src="${A}sec_action_pencil.jpg" class="pic" style="height:230px"><b>Take a pencil</b></button><button class="soft command" data-act="book"><img src="${A}sec_action_book.jpg" class="pic" style="height:230px"><b>Take a book</b></button></div><button class="pill blue" id="source-go" style="margin-top:16px">New command</button><div id="source-prompt" class="teacher"></div>`,el=>{const map={bag:'Put your bag away',pencil:'Take a pencil',book:'Take a book'};let t;function go(){t=Object.keys(map)[Math.floor(Math.random()*3)];el.querySelector('#source-prompt').textContent='TEACHER ONLY · '+map[t];}el.querySelector('#source-go').onclick=go;el.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>{if(b.dataset.act===t){b.classList.add('good');sfx('sfx_correct.mp3');toast('Action understood');}else{b.classList.add('bad');setTimeout(()=>b.classList.remove('bad'),350);}});return{onEnter:go};});

addScreen('use survival phrases',`<div class="big">Your power words</div><div class="grid" style="grid-template-columns:repeat(3,1fr);max-width:1050px;margin-top:28px"><button class="pill command" data-audio="a_r_okay.wav"><strong>Okay.</strong><span class="ar">حسنًا</span><small>I understand.</small></button><button class="pill command" data-audio="a_r_again.wav"><strong>Again, please.</strong><span class="ar">مرة أخرى، من فضلك</span><small>Say it one more time.</small></button><button class="pill command" data-audio="a_r_help.wav"><strong>Help, please.</strong><span class="ar">ساعدني، من فضلك</span><small>I need help.</small></button></div><div class="sub">Hear it → repeat twice → use it with your teacher.</div>`);

addScreen('choose the right help phrase',`<div class="row"><img src="${A}sec_teacher.png" class="pic" style="width:310px;height:420px"><div style="max-width:650px"><div class="soft" style="font-size:28px"><b>The teacher speaks too fast.</b><div class="ar">المعلمة تتكلم بسرعة.</div></div><button class="speaker" data-audio="a_r_fast.wav" style="margin:18px"></button><div class="grid" style="grid-template-columns:1fr 1fr"><button class="pill" data-right="0">Okay.</button><button class="pill" data-right="1">Again, please.</button></div></div></div>`,el=>{el.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{if(b.dataset.right==='1'){b.classList.add('good');play('a_r_again.wav');toast('Great self-help!');}else{b.classList.add('bad');setTimeout(()=>b.classList.remove('bad'),350);}});return{};});

addScreen('complete the 60-second mission',`<div class="big">Classroom Mission</div><div id="mission-time" style="font-size:64px;color:#ff8c42;font-weight:900;margin:14px">60</div><div id="mission-command" class="soft" style="min-width:540px;text-align:center;font-size:38px;font-weight:800">Press Start</div><div class="row" style="margin-top:20px"><button class="pill blue" id="mission-start">Start</button><button class="pill green" id="mission-done">I did it</button><button class="pill" id="mission-help">Again, please.</button></div><div id="mission-score" class="sub">Actions: 0</div>`,el=>{let sec=60,count=0,c='';function next(){c=commands[Math.floor(Math.random()*commands.length)];el.querySelector('#mission-command').textContent=c;play(audio[c]);}el.querySelector('#mission-start').onclick=()=>{clearInterval(liveTimer);sec=60;count=0;next();liveTimer=setInterval(()=>{sec--;el.querySelector('#mission-time').textContent=sec;if(sec<=0){clearInterval(liveTimer);toast(`Mission complete: ${count} actions`);sfx('sfx_success.mp3');}},1000);};el.querySelector('#mission-done').onclick=()=>{count++;el.querySelector('#mission-score').textContent=`Actions: ${count}`;next();};el.querySelector('#mission-help').onclick=()=>{play('a_r_again.wav');setTimeout(()=>play(audio[c]),800);};return{onLeave(){clearInterval(liveTimer);}};});

addScreen('Check 1 — respond independently',`<div class="big">Check 1 · Five commands</div><div id="check-command" class="soft" style="font-size:44px;font-weight:900;min-width:560px;text-align:center;margin:16px">Listen only</div><button class="speaker" id="check-play"></button><div class="row" style="margin-top:16px"><button class="grade" data-g="A">Did it</button><button class="grade" data-g="B">Needed help</button><button class="grade" data-g="C">Not yet</button></div><div id="check-count" class="sub">1 / 5</div><div id="error-box" style="display:none;margin-top:12px" class="soft"><b>Error type:</b> <button class="pill" data-e="meaning">Meaning</button> <button class="pill" data-e="attention">Attention</button> <button class="pill" data-e="action">Wrong action</button></div>`,el=>{let list=[],n=0;function render(){const c=list[n];el.querySelector('#check-command').textContent='Listen. Do it.';el.querySelector('#check-count').textContent=`${n+1} / 5`;el.querySelector('#error-box').style.display='none';play(audio[c]);}el.querySelector('#check-play').onclick=()=>play(audio[list[n]]);el.querySelectorAll('.grade').forEach(b=>b.onclick=()=>{result.check1.push({command:list[n],grade:b.dataset.g});if(b.dataset.g==='A'){n++;if(n<5)render();else finish();}else el.querySelector('#error-box').style.display='block';});el.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{result.errors.push({command:list[n],type:b.dataset.e});n++;if(n<5)render();else finish();});function finish(){el.querySelector('#check-command').textContent=`Check 1 complete · ${result.check1.filter(x=>x.grade==='A').length}/5 independent`;sfx('sfx_success.mp3');}return{onEnter(){result.check1=[];result.errors=[];list=shuffle(commands).slice(0,5);n=0;render();}};});

addScreen('fixed rescue, then Check 2',`<div class="big">Rescue path</div><div class="sub">Follow every step in order. Then hide help and retry.</div><div class="row" id="rescue-steps" style="margin:20px 0">${['Replay','Teacher acts','Student copies','Show picture','Say together','Fade help','Retry'].map((x,i)=>`<button class="step" title="${x}">${i+1}</button>`).join('')}</div><div class="soft" id="rescue-label" style="font-size:26px;min-width:520px;text-align:center">1 · Replay slowly</div><div class="row" style="margin-top:18px"><button class="pill blue" id="retry-play">Hidden-answer retry</button></div><div id="band-box" style="display:none;margin-top:18px">${gradeButtons('band-grade')}</div>`,el=>{const labels=['Replay slowly','Teacher acts','Student copies','Show one picture','Say it together','Fade the help','Retry with no help'];let idx=0,retry=0,list=[];el.querySelectorAll('.step').forEach((b,i)=>b.onclick=()=>{if(i===idx){b.classList.add('done');el.querySelector('#rescue-label').textContent=`${i+1} · ${labels[i]}`;idx++;if(idx===7){el.querySelector('#band-box').style.display='block';toast('Now Check 2');}}});el.querySelector('#retry-play').onclick=()=>{const c=list[retry%5];play(audio[c]);retry++;};el.querySelectorAll('.grade').forEach(b=>b.onclick=()=>{result.band=b.dataset.g==='A'?'A · Independent':b.dataset.g==='B'?'B · With help':'C · Rebuild needed';el.querySelectorAll('.grade').forEach(x=>x.classList.toggle('selected',x===b));toast('Final band saved');});return{onEnter(){idx=0;retry=0;list=shuffle(commands).slice(0,5);el.querySelectorAll('.step').forEach(b=>b.classList.remove('done'));el.querySelector('#band-box').style.display='none';el.querySelector('#rescue-label').textContent='1 · Replay slowly';}};});

addScreen('practice school-test formats',`<div class="big">School Practice</div><div class="sub">Follow the arrow. Then match.</div><div class="grid" style="grid-template-columns:repeat(3,1fr);max-width:1080px;margin-top:20px"><div class="soft"><div style="font-size:70px;text-align:center">→</div><button class="pill" data-school="book">BOOK</button><button class="pill" data-school="pencil">PENCIL</button></div><div class="soft" style="text-align:center"><img src="${A}sec_action_book.jpg" class="pic" style="height:230px"><div><button class="pill" data-school="book">Open book</button></div></div><div class="soft" style="text-align:center"><img src="${A}sec_action_pencil.jpg" class="pic" style="height:230px"><div><button class="pill" data-school="pencil">Take pencil</button></div></div></div>`,el=>{el.querySelectorAll('[data-school]').forEach(b=>b.onclick=()=>{b.classList.add('good');sfx('sfx_correct.mp3');});return{};});

addScreen('see progress and teacher notes',`<div class="row"><div class="soft" style="width:620px"><div class="big" style="text-align:left">I am ready!</div><div style="font-size:25px;line-height:1.8;margin-top:14px">I can listen and act.<br>I can say <b>Again, please.</b><br>I can say <b>Help, please.</b></div><div class="ar sub" style="text-align:right">أنا مستعد للحصة.</div></div><div class="soft" style="width:360px"><div class="tag">TEACHER RECORD</div><div id="summary" style="font-size:22px;line-height:1.8;margin-top:14px"></div><details style="margin-top:12px"><summary>Baseline notes</summary><p>Hello/name: <span id="base-value"></span></p><p>Also record colors, initial sound, attention in CRM.</p></details></div></div>`,el=>({onEnter(){el.querySelector('#summary').innerHTML=`Final level: <b>${result.band}</b><br>Check 1: ${result.check1.filter(x=>x.grade==='A').length}/5 independent<br>Rescue focus: ${result.errors.map(x=>x.type).join(', ')||'none'}`;el.querySelector('#base-value').textContent=result.baseline.hello||'not recorded';}}));

addScreen('exit ticket and home review',`<div class="row"><div style="max-width:650px"><div class="big" style="text-align:left">One last command!</div><button class="speaker" id="exit-play" style="margin:20px 0"></button><div class="soft" style="font-size:27px;line-height:1.7"><b>Exit:</b> listen and act with no help.<br><b>Home:</b> teach one class word to your family.<div class="ar">في البيت: علّم كلمة صفية واحدة لعائلتك.</div></div><a class="pill blue" href="review/" style="display:inline-block;text-decoration:none;margin-top:20px">Open home review</a></div><div class="soft" style="width:340px;text-align:center"><img src="${A}sec_char_noura.png" class="pic" style="height:300px"><div style="font-size:25px;font-weight:800">Ready for We Can!</div></div></div>`,el=>{let c='Look';return{onEnter(){c=commands[Math.floor(Math.random()*commands.length)];el.querySelector('#exit-play').onclick=()=>play(audio[c]);play(audio[c]);}};});

screens.forEach((s,i)=>{const b=document.createElement('button');b.textContent=`${i+1} · ${s.objective}`;b.onclick=()=>{$('#thumbs').classList.remove('open');show(i);};$('#thumbs').appendChild(b);});
const startPage=Math.max(0,Math.min(16,(Number(new URLSearchParams(location.search).get('page'))||1)-1));
fit();show(startPage);
