/* We Can 1 · Unit 1 L6 · Global Lesson 7 · My First Friend Show · baseline v2.1
 * 内容源：WeCan1_Lesson1-7_二级教学蓝图_v1.md · Lesson 7
 * 过关标准：New Friend Day 场景 60–90 秒分站交流六项（问候/姓名/状态/三色 Hunt/姓名卡/告别），
 *          至少 4 项独立完成；每项分别记 A/B/C，不用总分掩盖短板。
 * 边界：单元整合输出课，不新增核心语言；家庭展示自愿，不作过关条件。
 * book=We Can 1 / unit=Unit 1 / lesson=L6 / lessonKey=wc1-u1-l6 */
const A='assets/',$=s=>document.querySelector(s);let cur=0,curAudio=null,toastTimer,liveTimer=null;
const screens=[],host=$('#screens');

const css=document.createElement('style');css.textContent=`
.layout{width:1080px;display:grid;grid-template-columns:1fr 1fr;gap:48px;align-items:center}.row{width:100%;display:flex;align-items:center;justify-content:center;gap:22px}.grid{width:100%;display:grid;gap:18px}.stack{display:grid;gap:16px}.card{background:rgba(255,255,255,.97);border:1px solid rgba(23,50,77,.06);border-radius:30px;box-shadow:var(--shadow)}.copy{padding:34px 38px}.title{font-size:56px;line-height:1.06;letter-spacing:-1.4px;font-weight:900}.title.sm{font-size:46px}.subtitle{margin-top:12px;color:var(--muted);font-size:22px;line-height:1.4}.accent{color:var(--coral)}.media{overflow:hidden;border-radius:30px;box-shadow:var(--shadow);background:#fff}.media img{width:100%;height:100%;object-fit:cover;display:block}.source-badge{display:inline-block;padding:9px 15px;border-radius:13px;background:var(--sun);font-size:16px;font-weight:900;box-shadow:0 5px 0 #e3b829}
.goal-card{height:165px;padding:25px;display:flex;flex-direction:column;justify-content:space-between}.goal-card .letter{font-size:18px;color:var(--blue);font-weight:900}.goal-card strong{font-size:30px}.goal-card p{color:var(--muted);font-size:18px}.mini-pill{border:0;border-radius:999px;padding:13px 20px;background:#fff;color:var(--navy);box-shadow:0 8px 24px rgba(23,50,77,.1);font-size:18px;font-weight:850;cursor:pointer}.mini-pill.blue{background:var(--blue);color:#fff}.mini-pill.green{background:var(--green);color:#fff}.mini-pill:active{transform:translateY(2px)}
.ltr-card{border:0;border-radius:24px;background:#fff;box-shadow:var(--shadow);cursor:pointer;padding:13px 8px;text-align:center;transition:transform .12s;min-width:120px}.ltr-card:active{transform:translateY(3px)}.ltr-card .big{font-size:60px;font-weight:900;line-height:1}.ltr-card .nm{margin-top:6px;font-size:16px;color:var(--muted);font-weight:800}
.word-opt{min-width:150px;padding:16px 22px;border:0;border-radius:20px;background:#fff;color:var(--navy);box-shadow:var(--shadow);font-size:30px;font-weight:900;cursor:pointer}.phrase-opt{min-width:280px;padding:18px 26px;border:0;border-radius:22px;background:#fff;color:var(--navy);box-shadow:var(--shadow);font-size:28px;font-weight:850;cursor:pointer}.good{outline:6px solid var(--green)!important;background:#ecfff6!important}.bad{animation:shake .35s}.selected{outline:5px solid var(--sun)}
.balloon{position:absolute;width:96px;cursor:pointer;transition:transform .15s;filter:drop-shadow(0 10px 18px rgba(23,50,77,.18));animation:floaty 3.2s ease-in-out infinite}.balloon:active{transform:scale(.86)}@keyframes floaty{50%{transform:translateY(-14px)}}@keyframes shake{25%{transform:translateX(-9px)}75%{transform:translateX(9px)}}
.dots{display:flex;gap:12px;justify-content:center;margin-top:18px}.dot{width:13px;height:13px;border-radius:50%;background:#d8e1e7}.dot.done{background:var(--green)}
.grade{padding:10px 14px;border:0;border-radius:13px;color:#fff;font-weight:850;cursor:pointer}.grade[data-g=A]{background:var(--green)}.grade[data-g=B]{background:#f0a52b}.grade[data-g=C]{background:var(--red)}.error{padding:9px 12px;border:0;border-radius:12px;background:#fff;color:var(--navy);font-weight:800;cursor:pointer}.teacher-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.steps{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.step{height:40px;padding:0 12px;border:2px solid rgba(255,255,255,.25);border-radius:999px;background:transparent;color:#fff;font-weight:800;cursor:pointer}.step.done{background:var(--green);border-color:var(--green)}
.support{min-height:110px;margin-top:16px;padding:18px 22px;border-radius:22px;background:#fff;box-shadow:var(--shadow);font-size:26px;font-weight:850;text-align:center;display:grid;place-items:center}.support:empty{visibility:hidden}
.swatch-chip{width:120px;height:120px;border:6px solid #fff;border-radius:26px;box-shadow:var(--shadow);cursor:pointer}.swatch-chip:active{transform:translateY(3px)}
.mission{width:960px;text-align:center}.timer-big{font-size:56px;font-weight:900;color:var(--coral)}
.bubble{position:relative;background:#fff;border-radius:24px;padding:16px 24px;box-shadow:var(--shadow);font-size:28px;font-weight:850;display:inline-block;text-align:left}.bubble:after{content:"";position:absolute;bottom:-13px;left:42px;border:8px solid transparent;border-top:13px solid #fff}.bubble.right:after{left:auto;right:42px}.bubble.qm{font-size:52px;color:var(--coral);padding:10px 30px}
.chip{display:flex;flex-direction:column;align-items:center;gap:6px;padding:14px 8px;border-radius:22px;background:#fff;box-shadow:var(--shadow);border-top:10px solid var(--line);opacity:.4;transition:all .2s}.chip.on{opacity:1;border-top-color:var(--coral);transform:translateY(-6px)}.chip.done{opacity:1;border-top-color:var(--green)}.chip .ic{height:52px;display:grid;place-items:center}.chip strong{font-size:17px;text-align:center}
.map-row{display:flex;align-items:stretch;gap:10px;width:1080px;margin-top:24px}.map-row .arr{display:grid;place-items:center}
.invite{width:480px;background:linear-gradient(160deg,#fff,#fff7e6);border-radius:30px;box-shadow:var(--shadow);padding:34px;text-align:center;border-top:14px solid var(--coral)}.invite h2{font-size:44px;margin:8px 0 0}.invite .env{font-size:64px}
.namecard{width:330px;background:#fff;border-radius:22px;box-shadow:var(--shadow);padding:22px;text-align:center;border:5px dashed var(--blue)}.namecard .nm{font-size:46px;font-weight:900;color:var(--navy);letter-spacing:2px}.namecard .fl{font-size:70px;font-weight:900;color:var(--coral);line-height:1}
.g-badge{display:inline-block;min-width:34px;padding:3px 10px;border-radius:999px;color:#fff;font-weight:900}.g-A{background:var(--green)}.g-B{background:#f0a52b}.g-C{background:var(--red)}.g-none{background:#b6c4cf}
.ability6{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;width:1020px}.ability6 .card{padding:20px 14px;text-align:center}.ability6 .ic{height:56px;display:grid;place-items:center}.ability6 strong{display:block;margin-top:8px;font-size:19px}.result-line{margin-top:8px;font-size:15px;color:var(--muted)}
.char-row{display:flex;align-items:flex-end;gap:26px;justify-content:center}.char-row img{height:250px;object-fit:contain;filter:drop-shadow(0 12px 20px rgba(23,50,77,.18))}
.stage-col{display:flex;flex-direction:column;align-items:center;gap:18px}
`;document.head.appendChild(css);

function play(src){stopAudio();curAudio=new Audio(A+src);curAudio.play().catch(()=>{});}function stopAudio(){if(curAudio){curAudio.pause();curAudio.currentTime=0;curAudio=null;}}function sfx(src){new Audio(A+src).play().catch(()=>{});}function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1400);}function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function addScreen(title,html,init,{assessment=false}={}){const el=document.createElement('section');el.className='screen'+(assessment?' assessment':'');el.innerHTML=html;host.appendChild(el);const api=init?init(el):{};screens.push({title,el,...api});}
function show(i){i=Math.max(0,Math.min(screens.length-1,i));screens[cur]?.onLeave?.();stopAudio();clearInterval(liveTimer);cur=i;screens.forEach((s,n)=>s.el.classList.toggle('active',n===i));$('#objective').textContent=screens[i].title;$('#page-num').textContent=`${i+1} / ${screens.length}`;$('#progress').style.width=`${(i+1)/screens.length*100}%`;$('#btn-prev').disabled=i===0;$('#btn-next').disabled=i===screens.length-1;document.querySelectorAll('#thumbs button').forEach((b,n)=>b.classList.toggle('cur',n===i));screens[i].onEnter?.()}
function fit(){const z=Math.min(innerWidth/1280,innerHeight/720);$('#stage').style.transform=`scale(${z})`}addEventListener('resize',fit);
$('#btn-ar').onclick=()=>{const on=document.body.classList.toggle('ar-on');$('#btn-ar').setAttribute('aria-pressed',String(on))};$('#btn-teacher').onclick=()=>{const on=document.body.classList.toggle('teacher-on');$('#btn-teacher').setAttribute('aria-pressed',String(on))};$('#btn-prev').onclick=()=>show(cur-1);$('#btn-next').onclick=()=>show(cur+1);$('#btn-pages').onclick=()=>$('#thumbs').classList.toggle('open');$('#btn-fs').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>{});document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')show(cur+1);if(e.key==='ArrowLeft')show(cur-1)});host.addEventListener('click',e=>{const b=e.target.closest('[data-audio]');if(b)play(b.dataset.audio)});

/* ---------- 课程数据 ---------- */
const KEY8='ABCDEFGH'.split('');
const TILE={A:'#ef3f36',B:'#ff9f2e',C:'#e8a200',D:'#37b56a',E:'#2f80ed',F:'#8e5bd6',G:'#ff6fb5',H:'#8d6e63'};
const COLORS=[{en:'red',hex:'#ef3f36',ar:'أحمر'},{en:'yellow',hex:'#ffd93b',ar:'أصفر'},{en:'blue',hex:'#2f80ed',ar:'أزرق'},{en:'green',hex:'#37b56a',ar:'أخضر'},{en:'purple',hex:'#8e5bd6',ar:'بنفسجي'}];
const CHARS={noura:{name:'Noura',img:'sec_char_noura.png',audio:'a_t_my_names_noura.mp3'},labeeb:{name:'Labeeb',img:'sec_labeeb_clean.png',audio:'a_t_my_names_labeeb.mp3'},omar:{name:'Omar',img:'sec_char_omar.png',audio:'a_t_my_names_omar.mp3'}};
const SIX=[{k:'greet',t:'Say hello',icon:'wave',hint:'Hello!'},{k:'askName',t:'Ask names',icon:'chat',hint:"What's your name?"},{k:'askStatus',t:'How are you?',icon:'heart',hint:'How are you?'},{k:'colorHunt',t:'Find 3 colors',icon:'palette',hint:'Find red!'},{k:'nameCard',t:'Show name card',icon:'card',hint:'This is my name card.'},{k:'goodbye',t:'Say good-bye',icon:'bye',hint:'Good-bye!'}];
const FINAL_ORDER=['greet','askName','askStatus','nameCard','colorHunt','goodbye'];
const ERR6=['Silence','Name Q&A mix','Status mix','Needs script','Arabic only'];
const results={show:{greet:null,askName:null,askStatus:null,colorHunt:null,nameCard:null,goodbye:null},check2:{},errors:[],rushHits:0,finalNote:''};
let stuName='';
function noAr(){document.body.classList.remove('ar-on');$('#btn-ar').setAttribute('aria-pressed','false')}
function ltrBtn(L){return `<button class="word-opt" data-w="${L}" style="color:${TILE[L]}">${L}</button>`}
function swBtn(c){return `<button class="swatch-chip" data-w="${c.en}" style="background:${c.hex}"></button>`}
function balloonCol(c,x,y){return `<svg class="balloon" data-w="${c.en}" style="left:${x}px;top:${y}px" viewBox="0 0 96 120"><ellipse cx="48" cy="46" rx="40" ry="44" fill="${c.hex}"/><polygon points="48,92 40,106 56,106" fill="${c.hex}"/></svg>`}
function balloonLtr(L,x,y){return `<svg class="balloon" data-w="${L}" style="left:${x}px;top:${y}px" viewBox="0 0 96 120"><ellipse cx="48" cy="46" rx="40" ry="44" fill="#ffffff" stroke="${TILE[L]}" stroke-width="5"/><text x="48" y="60" text-anchor="middle" font-size="40" font-weight="900" fill="${TILE[L]}">${L}</text><polygon points="48,92 40,106 56,106" fill="#ffffff" stroke="${TILE[L]}" stroke-width="4"/></svg>`}
const ARROW='<svg width="60" height="34" viewBox="0 0 74 40"><path d="M4 20 H56 M44 6 L60 20 L44 34" stroke="#ff735e" stroke-width="9" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>';
function icSVG(k){const m={wave:'<svg width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="#ff735e" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 12V5.5a1.5 1.5 0 0 1 3 0V11m0-6.5v-1a1.5 1.5 0 0 1 3 0V11m0-5.5a1.5 1.5 0 0 1 3 0V12m0-4a1.5 1.5 0 0 1 3 0v5a7 7 0 0 1-7 7h-1a7 7 0 0 1-6-3.3L4.6 17a1.6 1.6 0 0 1 .4-2.6 1.6 1.6 0 0 1 2 .4z"/></svg>',chat:'<svg width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="#1670e8" stroke-width="2"><path d="M21 12a8 8 0 0 1-8 8H4l2-3a8 8 0 1 1 15-5z"/><path d="M8.5 12h.01M12 12h.01M15.5 12h.01" stroke-linecap="round" stroke-width="3"/></svg>',heart:'<svg width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="#ff6fb5" stroke-width="2" stroke-linejoin="round"><path d="M12 20s-7-4.6-9.3-9A5.2 5.2 0 0 1 12 6.5 5.2 5.2 0 0 1 21.3 11C19 15.4 12 20 12 20z"/></svg>',palette:'<svg width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="#37b56a" stroke-width="2"><path d="M12 3a9 9 0 1 0 0 18c1.5 0 2-1 1.4-2.2-.7-1.3.1-2.3 1.6-2.3H17a4 4 0 0 0 4-4c0-5.2-4-9.5-9-9.5z"/><circle cx="7.5" cy="11.5" r="1.3" fill="#2f80ed" stroke="none"/><circle cx="12" cy="7.5" r="1.3" fill="#37b56a" stroke="none"/><circle cx="16.5" cy="11.5" r="1.3" fill="#ffd93b" stroke="none"/></svg>',card:'<svg width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="#8e5bd6" stroke-width="2"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="M7 15v-4m0 0l2 2m-2-2l-2 2M13 11h4m-4 4h4" stroke-linecap="round"/></svg>',bye:'<svg width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="#f0a52b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 4h5a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1h-5M10 17l5-5-5-5M15 12H3"/></svg>'};return m[k]}
function chipHTML(k,cls=''){const s=SIX.find(x=>x.k===k);return `<div class="chip ${cls}" data-chip="${k}"><div class="ic">${icSVG(s.icon)}</div><strong>${s.t}</strong></div>`}
function charImg(ck,h=250){const c=CHARS[ck];return `<img src="${A}${c.img}" style="height:${h}px;object-fit:contain;filter:drop-shadow(0 12px 20px rgba(23,50,77,.18))" alt="${c.name}">`}

/* S1 · 课前须知（全阿语，版式统一） */
addScreen('أهلاً · Get ready',`<div style="width:940px;text-align:center"><h1 class="title">My First Friend Show<span style="color:var(--coral)"> · </span><span style="color:var(--blue)">عرض صديقي الأول</span></h1><p class="subtitle" style="font-size:24px">الصوت واضح، وبطاقة الاسم والألوان بالقرب منك</p><div class="grid" style="grid-template-columns:repeat(3,1fr);margin-top:34px"><div class="card goal-card"><span class="letter">01</span><strong>الصوت</strong><p>شغّل الميكروفون</p></div><div class="card goal-card"><span class="letter">02</span><strong>بطاقة الاسم</strong><p>Name Card جاهزة</p></div><div class="card goal-card"><span class="letter">03</span><strong>الألوان</strong><p>أشياء ملوّنة حولك</p></div></div><div class="row" style="margin-top:30px"><button class="mini-pill blue" data-audio="a_t_soundcheck.mp3">اختبار الصوت</button></div></div>`,null);

/* S2 · Lead-in：邀请函 + L5 最低维度定向提取（教师面板选维度，默认随机） */
addScreen('Invitation · New Friend Day',`<div class="layout" style="grid-template-columns:1fr 1.1fr"><div class="invite"><div class="env">✉️</div><span class="source-badge">YOU ARE INVITED</span><h2>New Friend Day</h2><p class="subtitle">Meet a new friend. Talk. Show. <button class="speaker small" data-audio="a_t_new_friend_day.mp3" style="vertical-align:middle"></button></p><p class="ar subtitle">يوم الصديق الجديد — ستقابل صديقاً جديداً اليوم</p></div><div class="card copy" style="text-align:center"><h2 style="font-size:30px;margin-top:0">One warm-up first</h2><div id="wu-stage" style="min-height:230px;display:grid;place-items:center"></div></div></div><div class="teacher"><b>定向提取（限 2 分钟）</b>：默认已随机抽取一个维度；若系统/上节课记录了最低维度，点下方按钮切换成它。学生<b>先说后点</b>；卡住只给一次慢音，不长补——本课重点是综合输出。<div class="teacher-row"><span>Warm-up:</span><button class="error" data-wu="qa">问答</button><button class="error" data-wu="sit">情境</button><button class="error" data-wu="col">颜色</button><button class="error" data-wu="ltr">字母</button></div></div>`,el=>{
 const stage=el.querySelector('#wu-stage');
 const TASKS={
  qa(){stage.innerHTML=`<div class="stage-col"><div class="row" style="width:auto"><button class="speaker large" id="wu-play"></button><b style="font-size:24px">Say YOUR answer, then tap it</b></div><div class="row" id="wu-opts"></div></div>`;stage.querySelector('#wu-play').onclick=()=>play('a_t_whats_your_name.mp3');play('a_t_whats_your_name.mp3');stage.querySelector('#wu-opts').innerHTML=shuffle(["My name's ___.","I'm fine, thank you."]).map(t=>`<button class="phrase-opt" data-w="${t}">${t}</button>`).join('');bind("My name's ___.",null,'a_t_my_names_noura.mp3')},
  sit(){stage.innerHTML=`<div class="stage-col"><b style="font-size:24px">School is over. What do you say?</b><div class="row" id="wu-opts"></div></div>`;stage.querySelector('#wu-opts').innerHTML=shuffle(['Good-bye. See you again.','Good morning.']).map(t=>`<button class="phrase-opt" data-w="${t}">${t}</button>`).join('');bind('Good-bye. See you again.',null,'a_t_goodbye_seeyou.mp3')},
  col(){const c=shuffle(COLORS)[0];stage.innerHTML=`<div class="stage-col"><div class="row" style="width:auto"><button class="speaker large" id="wu-play"></button><b style="font-size:24px">Tap the color you hear</b></div><div class="row" id="wu-opts"></div></div>`;stage.querySelector('#wu-play').onclick=()=>play(`a_t_${c.en}.mp3`);play(`a_t_${c.en}.mp3`);stage.querySelector('#wu-opts').innerHTML=shuffle([c,...shuffle(COLORS.filter(x=>x.en!==c.en)).slice(0,2)]).map(swBtn).join('');bind(c.en,null,`a_t_${c.en}.mp3`)},
  ltr(){const L=shuffle(KEY8)[0];stage.innerHTML=`<div class="stage-col"><div class="row" style="width:auto"><button class="speaker large" id="wu-play"></button><b style="font-size:24px">Tap the letter you hear</b></div><div class="row" id="wu-opts"></div></div>`;stage.querySelector('#wu-play').onclick=()=>play(`a_t_ltr_${L}.mp3`);play(`a_t_ltr_${L}.mp3`);stage.querySelector('#wu-opts').innerHTML=shuffle([L,...shuffle(KEY8.filter(x=>x!==L)).slice(0,2)]).map(ltrBtn).join('');bind(L,null,`a_t_ltr_${L}.mp3`)}
 };
 function bind(right,slow,okAudio){let done=false;stage.querySelectorAll('#wu-opts [data-w]').forEach(b=>b.onclick=()=>{if(done)return;done=true;if(b.dataset.w===right){b.classList.add('good');sfx('sfx_correct.mp3');if(okAudio)setTimeout(()=>play(okAudio),500)}else{b.classList.add('bad');sfx('sfx_wrong.mp3');setTimeout(()=>b.classList.remove('bad'),350);done=false}})}
 el.querySelectorAll('[data-wu]').forEach(b=>b.onclick=()=>TASKS[b.dataset.wu]());
 return{onEnter(){TASKS[shuffle(['qa','sit','col','ltr'])[0]]()}}});

/* S3 · New Friend Day 五站地图 + 六件事（权威承诺页） */
addScreen('The map · five stops',`<div class="mission"><span class="source-badge">NEW FRIEND DAY</span><h1 class="title sm" style="margin-top:14px">Five stops. Six things. <button class="speaker small" data-audio="a_t_six_things.mp3" style="vertical-align:middle"></button></h1><div class="map-row">${[['wave','Meet','Say hello first'],['chat','Ask','Names & feelings'],['palette','Find','Three colors'],['card','Show','Your name card'],['bye','Good-bye','End nicely']].map(([ic,t,p],i)=>`${i?`<div class="arr">${ARROW}</div>`:''}<div class="chip" style="opacity:1;flex:1;border-top-color:${['#ff735e','#1670e8','#37b56a','#8e5bd6','#f0a52b'][i]}"><div class="ic">${icSVG(ic)}</div><strong>${t}</strong><p style="color:var(--muted);font-size:14px;margin:0">${p}</p></div>`).join('')}</div><p class="ar subtitle">خمس محطات — قابل، اسأل، ابحث، اعرض، ودّع</p></div><div class="teacher"><b>承诺页（90 秒）</b>：带学生沿箭头指读五站，说清规则——每站先听后说，<b>六件事至少 4 件独立完成即达标</b>，每件事单独记分。不展开教内容，指完翻页。</div>`,null);

/* S4 · 示例站 1：问候（教师示范，学生只看） */
addScreen('Watch · stop 1 hello',`<div style="text-align:center"><div class="row" style="justify-content:center;gap:16px"><span class="source-badge">WATCH · STOP 1</span><h1 class="title sm">Say hello first <button class="speaker small" data-audio="a_t_watch.mp3" style="vertical-align:middle"></button></h1></div><div class="char-row" style="margin-top:20px"><div class="stage-col">${charImg('noura')}<div class="bubble">Hello! <button class="speaker small" data-audio="a_t_hello.mp3" style="vertical-align:middle"></button></div></div><div class="stage-col">${charImg('omar')}<div class="bubble right">Hi! Hello! <button class="speaker small" data-audio="a_t_hello_slow.mp3" style="vertical-align:middle"></button></div></div></div><p class="ar subtitle">شاهد فقط — التحية أولاً</p></div><div class="teacher"><b>示范站 1（40 秒）</b>：点播两遍对话，学生只看只听。看完后问学生："First, what do we say?" 学生指 chip 或说 Hello 即过，不展开。</div>`,null);

/* S5 · 示例站 2：姓名 / 状态 */
addScreen('Watch · stop 2 ask',`<div style="text-align:center;width:1000px"><div class="row" style="justify-content:center;gap:16px"><span class="source-badge">WATCH · STOP 2</span><h1 class="title sm">Ask and answer</h1></div><div class="row" style="margin-top:18px;align-items:center"><div class="stage-col">${charImg('noura',220)}<span class="mini-pill" style="cursor:default">Noura</span></div><div class="stack" style="flex:1;max-width:560px;text-align:left"><div class="bubble">What's your name? <button class="speaker small" data-audio="a_t_whats_your_name.mp3" style="vertical-align:middle"></button></div><div class="bubble right" style="align-self:flex-end">My name's Noura. <button class="speaker small" data-audio="a_t_my_names_noura.mp3" style="vertical-align:middle"></button></div><div class="bubble">How are you? <button class="speaker small" data-audio="a_t_how_are_you.mp3" style="vertical-align:middle"></button></div><div class="bubble right" style="align-self:flex-end">I'm fine, thank you. <button class="speaker small" data-audio="a_t_im_fine.mp3" style="vertical-align:middle"></button></div></div></div></div><div class="teacher"><b>示范站 2（60 秒）</b>：四句逐一点播两遍，学生指认哪句是问、哪句是答。不做跟读要求——跟读在 S9 操练完成。</div>`,null);

/* S6 · 示例站 3：颜色 / 姓名卡 / 告别 */
addScreen('Watch · stop 3 find show bye',`<div style="text-align:center;width:1060px"><div class="row" style="justify-content:center;gap:16px"><span class="source-badge">WATCH · STOP 3</span><h1 class="title sm">Find. Show. Good-bye.</h1></div><div class="grid" style="grid-template-columns:1fr 1fr 1fr;margin-top:18px"><div class="card copy" style="text-align:center"><b style="font-size:22px">Find 3 colors <button class="speaker small" data-audio="a_t_find_color.mp3" style="vertical-align:middle"></button></b><div class="row" style="margin-top:12px;gap:12px">${COLORS.slice(0,3).map(c=>`<button class="swatch-chip" style="width:74px;height:74px;background:${c.hex}" data-audio="a_t_${c.en}.mp3"></button>`).join('')}</div></div><div class="card copy" style="text-align:center"><b style="font-size:22px">Show your card <button class="speaker small" data-audio="a_t_show_card.mp3" style="vertical-align:middle"></button></b><div class="namecard" style="width:230px;margin:12px auto 0;padding:14px"><div class="fl">N</div><div class="nm" style="font-size:28px">Noura</div></div></div><div class="card copy" style="text-align:center"><b style="font-size:22px">Say good-bye</b><div class="bubble" style="margin-top:14px;font-size:22px">Good-bye. See you again. <button class="speaker small" data-audio="a_t_goodbye_seeyou.mp3" style="vertical-align:middle"></button></div><div class="bubble right" style="margin-top:10px;font-size:22px">Nice to meet you. <button class="speaker small" data-audio="a_t_nice_meet.mp3" style="vertical-align:middle"></button></div></div></div></div><div class="teacher"><b>示范站 3（60 秒）</b>：三件事各示范一遍——听颜色点色块、举卡片说两句、挥手告别。姓名卡若学生没带实物，用屏幕卡代替，不卡住流程。</div>`,null);

/* S7 · 跨课听音气球（颜色 + 字母混合，6 轮） */
addScreen('Pop it · colors and letters',`<div style="width:1060px"><div class="row" style="justify-content:space-between"><div class="row" style="width:auto;gap:16px"><span class="source-badge">WARM-UP GAME</span><h1 class="title sm">Pop what you hear</h1></div><button class="mini-pill blue" id="bl-start">Start · 6 rounds</button></div><div id="bl-field" style="position:relative;height:400px;margin-top:10px"></div><div class="dots" id="bl-dots">${'<span class="dot"></span>'.repeat(6)}</div></div><div class="teacher"><b>跨课听音气球：颜色词与字母名混合 6 轮，选项每轮换位置。</b>6 中 4 即过。错误只慢音重播一次（Slow），不逐词重教——本屏是激活，不是新课。<div class="teacher-row"><button class="error" id="bl-slow">▶ Slow replay</button></div></div>`,el=>{const POS=[[60,40],[400,150],[740,30],[950,150]];let rounds=[],n=0,cur=null;const dots=[...el.querySelectorAll('#bl-dots .dot')];
 function balloonFor(t,x,y){return t.k==='col'?balloonCol(t.c,x,y):balloonLtr(t.L,x,y)}
 function layout(){const opts=shuffle([cur,...shuffle(POOL.filter(p=>p.id!==cur.id)).slice(0,3)]);el.querySelector('#bl-field').innerHTML=opts.map((p,i)=>balloonFor(p,POS[i][0],POS[i][1])).join('');el.querySelectorAll('.balloon').forEach(b=>b.onclick=()=>{if(!cur)return;if(b.dataset.w===cur.id){b.style.transform='scale(0)';sfx('sfx_correct.mp3');dots[n]?.classList.add('done');setTimeout(next,650)}else{b.style.animation='shake .35s';sfx('sfx_wrong.mp3');setTimeout(()=>b.style.animation='floaty 3.2s ease-in-out infinite',400)}})}
 function next(){n++;if(n>=6){cur=null;toast('Balloons clear');sfx('sfx_success.mp3');return}cur=rounds[n];layout();setTimeout(()=>play(cur.au),350)}
 const POOL=[...COLORS.map(c=>({k:'col',c,id:c.en,au:`a_t_${c.en}.mp3`,slow:`a_t_${c.en}_slow.mp3`})),...KEY8.map(L=>({k:'ltr',L,id:L,au:`a_t_ltr_${L}.mp3`,slow:`a_t_ltr_${L}_slow.mp3`}))];
 el.querySelector('#bl-start').onclick=()=>{rounds=[...shuffle(COLORS).slice(0,3).map(c=>POOL.find(p=>p.id===c.en)),...shuffle(KEY8).slice(0,3).map(L=>POOL.find(p=>p.id===L))];rounds=shuffle(rounds);n=-1;dots.forEach(d=>d.classList.remove('done'));next()};
 el.querySelector('#bl-slow').onclick=()=>{if(cur)play(cur.slow)};
 return{onEnter(){const preview=shuffle(POOL).slice(0,4);el.querySelector('#bl-field').innerHTML=preview.map((p,i)=>balloonFor(p,POS[i][0],POS[i][1])).join('');el.querySelectorAll('.balloon').forEach(b=>b.onclick=()=>play(POOL.find(p=>p.id===b.dataset.w).au))}}});

/* S8 · Guided Show 前半输入：问候 / 姓名 / 状态 句框 */
addScreen('Your show · part 1 input',`<div style="text-align:center;width:1020px"><div class="row" style="justify-content:center;gap:16px"><span class="source-badge">YOUR TURN · PART 1</span><h1 class="title sm">Hello · Name · Feelings <button class="speaker small" data-audio="a_t_your_turn.mp3" style="vertical-align:middle"></button></h1></div><div class="row" style="margin-top:18px;align-items:center"><div class="stage-col">${charImg('noura',230)}<span class="mini-pill" style="cursor:default">Noura</span></div><div class="stack" style="flex:1;max-width:600px;text-align:left"><div class="card" style="padding:16px 22px"><b style="font-size:24px">1 · Hello!</b> <button class="speaker small" data-audio="a_t_hello.mp3" style="vertical-align:middle"></button></div><div class="card" style="padding:16px 22px"><b style="font-size:24px">2 · What's your name?</b> <button class="speaker small" data-audio="a_t_whats_your_name.mp3" style="vertical-align:middle"></button><p style="font-size:24px;color:var(--blue);font-weight:850;margin:6px 0 0">→ My name's ___.</p></div><div class="card" style="padding:16px 22px"><b style="font-size:24px">3 · How are you?</b> <button class="speaker small" data-audio="a_t_how_are_you.mp3" style="vertical-align:middle"></button><p style="font-size:24px;color:var(--blue);font-weight:850;margin:6px 0 0">→ I'm fine, thank you.</p></div></div></div></div><div class="teacher"><b>前半输入（90 秒）</b>：三轮问答句框呈现，逐条点播。句框（My name's ___. / I'm fine, thank you.）是<b>支架</b>，S13 起会撤掉。只带读一遍，马上进 S9 操练。</div>`,null);

/* S9 · Guided Show 前半操练：Noura 问 → 学生带句框答 ×3 */
addScreen('Guided show · part 1',`<div style="text-align:center;width:1020px"><div class="row" style="justify-content:center;gap:16px"><span class="source-badge">GUIDED SHOW · PART 1</span><h1 class="title sm">Talk with Noura</h1></div><div class="row" style="margin-top:18px;align-items:center"><div class="stage-col">${charImg('noura',250)}<div class="bubble" id="gs-bubble" style="min-height:60px">…</div></div><div class="stage-col" style="flex:1;max-width:520px"><div class="support" id="gs-frame" style="margin-top:0"></div><div class="dots" id="gs-dots">${'<span class="dot"></span>'.repeat(3)}</div></div></div></div><div class="teacher"><b>前半操练（带句框）</b>：点 Play 让 Noura 开口 → 学生看着句框回答 → 教师确认回答完整后点 Heard it 进下一句。<b>学生卡住只给当前句首词一次</b>（如 My…），仍说不出也先推进，在 S13 记录。<div class="teacher-row"><button class="error" id="gs-play">▶ Play Noura</button><button class="error" id="gs-next" style="background:var(--sky)">Heard it · next ▶</button></div></div>`,el=>{
 const LINES=[{b:'Hello!',au:'a_t_hello.mp3',frame:'Hello!',hint:'Hel…'},{b:"What's your name?",au:'a_t_whats_your_name.mp3',frame:"My name's ___.",hint:'My…'},{b:'How are you?',au:'a_t_how_are_you.mp3',frame:"I'm fine, thank you.",hint:"I'm…"}];let i=0;const dots=[...el.querySelectorAll('#gs-dots .dot')];
 function render(){if(i>=3){el.querySelector('#gs-bubble').innerHTML='Great talking!';el.querySelector('#gs-frame').innerHTML='<b style="color:var(--green)">Part 1 clear!</b>';sfx('sfx_success.mp3');return}el.querySelector('#gs-bubble').innerHTML=`<span>${LINES[i].b}</span>`;el.querySelector('#gs-frame').innerHTML=`<span style="font-size:30px">${LINES[i].frame}</span>`}
 el.querySelector('#gs-play').onclick=()=>{if(i<3)play(LINES[i].au)};
 el.querySelector('#gs-next').onclick=()=>{if(i>=3)return;dots[i].classList.add('done');i++;render()};
 return{onEnter(){i=0;dots.forEach(d=>d.classList.remove('done'));render();setTimeout(()=>play(LINES[0].au),400)}}});

/* S10 · Guided Show 后半输入：找三色 / 姓名卡 / 告别 */
addScreen('Your show · part 2 input',`<div style="text-align:center;width:1060px"><div class="row" style="justify-content:center;gap:16px"><span class="source-badge">YOUR TURN · PART 2</span><h1 class="title sm">Find · Show · Good-bye</h1></div><div class="grid" style="grid-template-columns:1fr 1fr 1fr;margin-top:18px"><div class="card copy" style="text-align:center"><b style="font-size:22px">4 · Find 3 colors <button class="speaker small" data-audio="a_t_find_color.mp3" style="vertical-align:middle"></button></b><div class="row" style="margin-top:12px;gap:10px;flex-wrap:wrap">${COLORS.map(c=>`<button class="swatch-chip" style="width:64px;height:64px;background:${c.hex}" data-audio="a_t_${c.en}.mp3"></button>`).join('')}</div><p class="subtitle" style="font-size:16px">Hear the color → find it around you or on screen</p></div><div class="card copy" style="text-align:center"><b style="font-size:22px">5 · Show your card</b><p style="font-size:22px;color:var(--blue);font-weight:850;margin:10px 0 0">This is my name card. <button class="speaker small" data-audio="a_t_name_card.mp3" style="vertical-align:middle"></button></p><p style="font-size:22px;color:var(--blue);font-weight:850;margin:6px 0 0">My name's ___. <button class="speaker small" data-audio="a_t_my_names_noura.mp3" style="vertical-align:middle"></button></p></div><div class="card copy" style="text-align:center"><b style="font-size:22px">6 · Say good-bye</b><p style="font-size:22px;font-weight:850;margin:10px 0 0">Good-bye. See you again. <button class="speaker small" data-audio="a_t_goodbye_seeyou.mp3" style="vertical-align:middle"></button></p></div></div></div><div class="teacher"><b>后半输入（90 秒）</b>：三件事的句型各点播一遍。颜色允许指屏幕色块或身边实物；姓名卡两句连说（This is my name card. My name's ___.）。</div>`,null);

/* S11 · Guided Show 后半操练：找色 ×3 + 教师录姓名出卡 + 告别 */
addScreen('Guided show · part 2',`<div style="text-align:center;width:1040px"><div class="row" style="justify-content:center;gap:16px"><span class="source-badge">GUIDED SHOW · PART 2</span><h1 class="title sm">Find, show, say good-bye</h1></div><div class="card copy" style="margin-top:16px;min-height:300px"><div id="gp-stage" class="stage-col"></div></div></div><div class="teacher"><b>后半操练三步走</b>：①点 Play color 让学生找出听到的颜色（屏幕或实物均可）×3；②<b>输入学生英文名</b>生成姓名卡，学生举卡说两句；③学生主动挥手说 Good-bye，教师点 Heard it 完成。<div class="teacher-row"><button class="error" id="gp-color">▶ Play color</button><input id="gp-name" placeholder="Student name" style="border:2px solid rgba(255,255,255,.3);border-radius:12px;background:transparent;color:#fff;padding:9px 12px;font-size:16px;width:160px"><button class="error" id="gp-card">Make card</button><button class="error" id="gp-bye">▶ Good-bye model</button><button class="error" id="gp-done" style="background:var(--sky)">Heard it ✓</button></div></div>`,el=>{
 const stage=el.querySelector('#gp-stage');let picked=0,targets=shuffle(COLORS).slice(0,3),ci=0;
 function renderColors(){stage.innerHTML=`<b style="font-size:24px">Find the color you hear · ${picked}/3</b><div class="row" style="margin-top:14px">${shuffle(COLORS).map(swBtn).join('')}</div>`;stage.querySelectorAll('.swatch-chip').forEach(b=>b.onclick=()=>{if(b.dataset.w===targets[ci].en){b.classList.add('good');sfx('sfx_correct.mp3');picked++;ci++;if(picked<3){setTimeout(()=>{renderColors();play(`a_t_${targets[ci].en}.mp3`)},800)}else{setTimeout(renderCard,800)}}else{b.classList.add('bad');sfx('sfx_wrong.mp3');setTimeout(()=>b.classList.remove('bad'),350)}})}
 function renderCard(){const nm=stuName||'___';const fl=(stuName||'?')[0].toUpperCase();stage.innerHTML=`<div class="namecard"><div class="fl">${fl}</div><div class="nm">${nm}</div></div><p style="font-size:26px;font-weight:850;margin:14px 0 0">This is my name card. My name's ${nm}.</p>`}
 function renderBye(){stage.innerHTML=`<div class="bubble" style="font-size:34px">Good-bye. See you again! <button class="speaker small" data-audio="a_t_goodbye_seeyou.mp3" style="vertical-align:middle"></button></div>`}
 el.querySelector('#gp-color').onclick=()=>{if(picked<3)play(`a_t_${targets[ci].en}.mp3`)};
 el.querySelector('#gp-card').onclick=()=>{const v=el.querySelector('#gp-name').value.trim();if(v){stuName=v;localStorage.setItem('khusoosi:wc1-u1-l6:progress',v)}renderCard()};
 el.querySelector('#gp-bye').onclick=()=>play('a_t_goodbye_seeyou.mp3');
 el.querySelector('#gp-done').onclick=()=>{if(picked<3){toast('Colors first')}else if(!stage.querySelector('.bubble'))renderBye();else{stage.innerHTML='<b style="font-size:28px;color:var(--green)">Part 2 clear!</b>';sfx('sfx_success.mp3')}};
 return{onEnter(){stuName=stuName||localStorage.getItem('khusoosi:wc1-u1-l6:progress')||'';el.querySelector('#gp-name').value=stuName;picked=0;ci=0;targets=shuffle(COLORS).slice(0,3);renderColors();setTimeout(()=>play(`a_t_${targets[0].en}.mp3`),400)}}});

/* S12 · 60 秒四站综合闯关（问答/颜色/字母混合 8 题） */
addScreen('Show Rush · 60 seconds',`<div class="mission"><span class="source-badge">BEAT THE CLOCK</span><div class="timer-big" id="r-timer" style="margin-top:6px">60</div><div class="card copy" style="margin-top:8px;min-height:320px"><div id="r-prompt" class="row" style="gap:16px"></div><div class="row" id="r-opts" style="margin-top:18px;flex-wrap:wrap"></div></div><div class="row" style="margin-top:12px"><button class="mini-pill blue" id="r-start">Start rush</button><span class="subtitle" id="r-score" style="margin:0"></span></div></div><div class="teacher"><b>Show Rush：问答/颜色/字母混合 8 题，速度次于正确。</b>每题错后暂停：先点错误分类，再继续。选项每题换位，防位置猜测。<div class="teacher-row"><span>Mark error:</span>${ERR6.map(e=>`<button class="error" data-e="${e}">${e}</button>`).join('')}</div></div>`,el=>{
 const RUSH=[{t:'qa',v:0},{t:'col',v:'red'},{t:'ltr',v:'C'},{t:'col',v:'green'},{t:'qa',v:1},{t:'ltr',v:'F'},{t:'col',v:'blue'},{t:'ltr',v:'H'}];
 const QA=[{qA:'a_t_whats_your_name.mp3',ans:"My name's ___.",other:"I'm fine, thank you."},{qA:'a_t_how_are_you.mp3',ans:"I'm fine, thank you.",other:"My name's ___."}];
 let hits=0,ti=0,tleft=60,busy=false;
 function renderTask(){const t=RUSH[ti];const pr=el.querySelector('#r-prompt'),op=el.querySelector('#r-opts');let right='';
  if(t.t==='col'){pr.innerHTML=`<button class="speaker small" id="r-play"></button><b style="font-size:24px">Tap the color you hear</b>`;op.innerHTML=shuffle([t.v,...shuffle(COLORS.filter(c=>c.en!==t.v)).slice(0,3).map(c=>c.en)]).map(en=>swBtn(COLORS.find(c=>c.en===en))).join('');right=t.v;pr.querySelector('#r-play').onclick=()=>play(`a_t_${t.v}.mp3`);setTimeout(()=>play(`a_t_${t.v}.mp3`),300)}
  else if(t.t==='ltr'){pr.innerHTML=`<button class="speaker small" id="r-play"></button><b style="font-size:24px">Tap the letter you hear</b>`;op.innerHTML=shuffle([t.v,...shuffle(KEY8.filter(L=>L!==t.v)).slice(0,3)]).map(ltrBtn).join('');right=t.v;pr.querySelector('#r-play').onclick=()=>play(`a_t_ltr_${t.v}.mp3`);setTimeout(()=>play(`a_t_ltr_${t.v}.mp3`),300)}
  else{const item=QA[t.v];pr.innerHTML=`<button class="speaker small" id="r-play"></button><b style="font-size:24px">Say it, then tap the answer</b>`;op.innerHTML=shuffle([item.ans,item.other]).map(x=>`<button class="phrase-opt" data-w="${x}">${x}</button>`).join('');right=item.ans;pr.querySelector('#r-play').onclick=()=>play(item.qA);setTimeout(()=>play(item.qA),300)}
  busy=false;op.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>{if(busy)return;busy=true;if(b.dataset.w===right){b.classList.add('good');sfx('sfx_correct.mp3');hits++;el.querySelector('#r-score').textContent=`${hits} hits`}else{b.classList.add('bad');sfx('sfx_wrong.mp3')}ti++;if(ti<RUSH.length&&tleft>0)setTimeout(renderTask,800);else end()})}
 function end(){clearInterval(liveTimer);el.querySelector('#r-prompt').innerHTML=`<b style="font-size:30px;color:var(--green)">Rush over · ${hits} / ${RUSH.length}</b>`;el.querySelector('#r-opts').innerHTML='';results.rushHits=hits;sfx('sfx_success.mp3')}
 el.querySelector('#r-start').onclick=()=>{hits=0;ti=0;tleft=60;el.querySelector('#r-score').textContent='';el.querySelector('#r-timer').textContent='60';clearInterval(liveTimer);liveTimer=setInterval(()=>{tleft--;el.querySelector('#r-timer').textContent=tleft;if(tleft<=0)end()},1000);renderTask()};
 el.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{results.errors.push({screen:'S12',type:b.dataset.e});toast('Error marked: '+b.dataset.e)});
 return{onLeave(){clearInterval(liveTimer)}}});

/* ---------- S13–S14 共用：三项前半检测的提示内容 ---------- */
const CHECK1=[
 {k:'greet',b:'Hello!',au:'a_t_hello.mp3',expect:'Student greets back: Hello! / Hi!'},
 {k:'askName',b:"What's your name?",au:'a_t_whats_your_name.mp3',expect:"Student answers: My name's ___."},
 {k:'askStatus',b:'How are you?',au:'a_t_how_are_you.mp3',expect:"Student answers: I'm fine, thank you."}
];

/* S13 · Check 1：换角色 Labeeb，隐藏句框，前半三项 + 错误分类（无支架无阿语） */
addScreen('Check 1 · meet Labeeb',`<div style="text-align:center;width:1000px"><div class="row" style="justify-content:center;gap:16px"><span class="source-badge" style="background:var(--red);box-shadow:none">CHECK 1 · NO HELP</span><h1 class="title sm">A new friend: Labeeb</h1></div><div class="row" style="margin-top:18px;align-items:center"><div class="stage-col">${charImg('labeeb',260)}<div class="bubble qm" id="c1-bubble">?</div></div><div class="stage-col" style="flex:1;max-width:480px"><div class="support" id="c1-note" style="margin-top:0;min-height:80px;font-size:22px"></div><div class="dots" id="c1-dots">${'<span class="dot"></span>'.repeat(3)}</div></div></div></div><div class="teacher"><b>Check 1 独立检测（无句框、无阿语、无预演）</b>：点 Play 让 Labeeb 开口 → 学生<b>口头回应</b>（教师只听不代答）→ 点 Heard it 后定级 A/B/C；B/C 必须点一个错误分类再进下项。三项：问候回应 / 姓名问答 / 状态问答。<div class="teacher-row"><button class="error" id="c1-play">▶ Play Labeeb</button><button class="error" id="c1-heard" style="background:var(--sky)">Heard it · grade ▶</button></div><div class="teacher-row" id="c1-grade" style="display:none"><span id="c1-item"><b>Grade:</b></span><button class="grade" data-g="A">A · Independent</button><button class="grade" data-g="B">B · With help</button><button class="grade" data-g="C">C · Not yet</button></div><div class="teacher-row" id="c1-err" style="display:none"><span>Error:</span>${ERR6.map(e=>`<button class="error" data-e="${e}">${e}</button>`).join('')}</div></div>`,el=>{
 let i=0,graded=false;const dots=[...el.querySelectorAll('#c1-dots .dot')];
 function render(){if(i>=3){el.querySelector('#c1-bubble').textContent='✓';el.querySelector('#c1-note').innerHTML='<b style="color:var(--green)">Check 1 done</b>';el.querySelector('#c1-grade').style.display='none';el.querySelector('#c1-err').style.display='none';sfx('sfx_success.mp3');return}graded=false;el.querySelector('#c1-bubble').textContent='?';el.querySelector('#c1-note').textContent='';el.querySelector('#c1-grade').style.display='none';el.querySelector('#c1-err').style.display='none'}
 el.querySelector('#c1-play').onclick=()=>{if(i<3)play(CHECK1[i].au)};
 el.querySelector('#c1-heard').onclick=()=>{if(i>=3||graded)return;el.querySelector('#c1-item').innerHTML=`<b>${SIX.find(s=>s.k===CHECK1[i].k).t}:</b>`;el.querySelector('#c1-grade').style.display='flex'};
 el.querySelectorAll('#c1-grade .grade').forEach(b=>b.onclick=()=>{if(graded)return;graded=true;const g=b.dataset.g,k=CHECK1[i].k;results.show[k]={grade:g,errs:[]};if(g==='A'){dots[i].classList.add('done');i++;render()}else{el.querySelector('#c1-err').style.display='flex'}});
 el.querySelectorAll('#c1-err .error').forEach(b=>b.onclick=()=>{const k=CHECK1[i].k;results.show[k].errs.push(b.dataset.e);results.errors.push({screen:'S13',item:k,type:b.dataset.e});dots[i].classList.add('done');i++;render()});
 return{onEnter(){noAr();i=0;dots.forEach(d=>d.classList.remove('done'));render();setTimeout(()=>play(CHECK1[0].au),500)}}},{assessment:true});

/* S14 · 定向补救（固定 7 步）→ 第三角色 Omar Check 2 → Final Show（六图标、5 秒锁、次序调换） */
addScreen('Fix it · Check 2 · Final Show',`<div class="card copy" style="width:1020px;text-align:center"><div class="support" id="fx-support" style="box-shadow:none;border:2px dashed var(--line)"></div><div id="fx-stage" style="margin-top:14px;min-height:300px;display:grid;place-items:center"></div></div><div class="teacher"><b>三段固定流程：①只补 Check 1 失败项（7 步按顺序）；②Omar 平行 Check 2；③Final Show（5 秒后才可 Help，只给首词，不打断）。</b><div class="teacher-row" id="fx-pick"><span>Item:</span>${SIX.map(s=>`<button class="error" data-item="${s.k}">${s.t}</button>`).join('')}</div><div class="steps" id="fx-steps">${['Meaning','Slow','Contrast','Model','Build','Hide help','Try again'].map((x,i)=>`<button class="step" data-step="${i}">${i+1} · ${x}</button>`).join('')}</div><div id="fx-note" style="margin-top:10px">Pick an item that failed Check 1.</div><div class="teacher-row" id="c2-row" style="display:none"><span><b>Check 2 · Omar:</b></span><button class="grade" data-g="A">A · Independent</button><button class="grade" data-g="B">B · With help</button><button class="grade" data-g="C">C · Not yet</button></div><div class="teacher-row" id="final-row"><button class="error" id="final-start" style="background:var(--coral);color:#fff">▶ Start Final Show (Omar)</button><button class="error" id="final-help" style="display:none">Help (locked 5s)</button><span id="final-grade" style="display:none"><button class="grade" data-g="A">A</button><button class="grade" data-g="B">B</button><button class="grade" data-g="C">C</button></span></div></div>`,el=>{
 let item='greet',stepIdx=0,phase='pick',fi=0,helpTimer=null;
 const support=el.querySelector('#fx-support'),stage=el.querySelector('#fx-stage'),note=el.querySelector('#fx-note');
 const failedItems=()=>SIX.filter(s=>{const r=results.show[s.k];return r&&r.grade!=='A'}).map(s=>s.k);
 const ACT={
  greet:[()=>{support.innerHTML=`<div><b>Hello!</b><span class="ar" style="display:block;font-size:19px;color:var(--blue)">مرحباً — التحية أولاً</span></div>`;stage.innerHTML=charImg('noura',190)},
   ()=>{play('a_t_hello_slow.mp3');support.innerHTML='Slow — listen and say.'},
   ()=>{support.innerHTML='<div style="display:flex;gap:30px"><div>START talking → <b>Hello!</b></div><div>END talking → <b>Good-bye!</b></div></div>';stage.innerHTML=''},
   ()=>{play('a_t_hello.mp3');support.innerHTML='<b>Hello!</b> — say it with Noura.'},
   ()=>{support.innerHTML='Say it with the frame:';stage.innerHTML='<span style="font-size:48px;font-weight:900">Hel___!</span>'},
   ()=>{support.innerHTML='';stage.innerHTML='<b style="font-size:26px">No text. Noura says hello — you answer.</b>';play('a_t_hello.mp3')},
   ()=>tryAgain()],
  askName:[()=>{support.innerHTML=`<div><b>What's your name?</b><span class="ar" style="display:block;font-size:19px;color:var(--blue)">ما اسمك؟</span></div>`;stage.innerHTML=charImg('noura',190)},
   ()=>{play('a_t_whats_your_name_slow.mp3');support.innerHTML='Slow question — listen again.'},
   ()=>{support.innerHTML=`<div style="display:flex;gap:30px"><div><b>What's your name?</b><br>→ My name's ___.</div><div><b>How are you?</b><br>→ I'm fine.</div></div>`;stage.innerHTML=''},
   ()=>{play('a_t_whats_your_name.mp3');setTimeout(()=>play('a_t_my_names_noura.mp3'),1500);support.innerHTML="<b>What's your name?</b> → <b>My name's Noura.</b>"},
   ()=>{support.innerHTML='Say it with the frame:';stage.innerHTML='<span style="font-size:44px;font-weight:900">My name\'s ___.</span>'},
   ()=>{support.innerHTML='';stage.innerHTML='<b style="font-size:26px">No text. Listen and answer.</b>';play('a_t_whats_your_name.mp3')},
   ()=>tryAgain()],
  askStatus:[()=>{support.innerHTML=`<div><b>How are you?</b><span class="ar" style="display:block;font-size:19px;color:var(--blue)">كيف حالك؟</span></div>`;stage.innerHTML=charImg('noura',190)},
   ()=>{play('a_t_how_are_you_slow.mp3');support.innerHTML='Slow question — listen again.'},
   ()=>{support.innerHTML=`<div style="display:flex;gap:30px"><div><b>How are you?</b><br>→ I'm fine.</div><div><b>What's your name?</b><br>→ My name's ___.</div></div>`;stage.innerHTML=''},
   ()=>{play('a_t_how_are_you.mp3');setTimeout(()=>play('a_t_im_fine.mp3'),1500);support.innerHTML="<b>How are you?</b> → <b>I'm fine, thank you.</b>"},
   ()=>{support.innerHTML='Say it with the frame:';stage.innerHTML='<span style="font-size:44px;font-weight:900">I\'m ___, thank you.</span>'},
   ()=>{support.innerHTML='';stage.innerHTML='<b style="font-size:26px">No text. Listen and answer.</b>';play('a_t_how_are_you.mp3')},
   ()=>tryAgain()],
  colorHunt:[()=>{const c=COLORS[0];stage.innerHTML=`<button class="swatch-chip" style="background:${c.hex};width:150px;height:150px"></button>`;support.innerHTML=`<div><b>red</b><span class="ar" style="display:block;font-size:19px;color:var(--blue)">أحمر</span></div>`},
   ()=>{play('a_t_red_slow.mp3');support.innerHTML='Slow — listen again.'},
   ()=>{stage.innerHTML=`<div class="row">${swBtn(COLORS[0])}${swBtn(COLORS[2])}</div>`;support.innerHTML='<b>red</b> ≠ <b>blue</b>';stage.querySelectorAll('.swatch-chip').forEach(b=>b.onclick=()=>play(`a_t_${b.dataset.w}.mp3`))},
   ()=>{play('a_t_find_color.mp3');setTimeout(()=>play('a_t_red.mp3'),1500);support.innerHTML='<b>Find red!</b>'},
   ()=>{support.innerHTML='Say it with the frame:';stage.innerHTML='<span style="font-size:44px;font-weight:900">It is ___.</span>'},
   ()=>{support.innerHTML='';stage.innerHTML=`<div class="row">${shuffle(COLORS).slice(0,3).map(swBtn).join('')}</div>`;stage.querySelectorAll('.swatch-chip').forEach(b=>b.onclick=()=>play(`a_t_${b.dataset.w}.mp3`))},
   ()=>tryAgain()],
  nameCard:[()=>{support.innerHTML=`<div><b>This is my name card.</b><span class="ar" style="display:block;font-size:19px;color:var(--blue)">هذه بطاقة اسمي</span></div>`;stage.innerHTML=`<div class="namecard" style="width:230px;padding:14px"><div class="fl">N</div><div class="nm" style="font-size:26px">Noura</div></div>`},
   ()=>{play('a_t_name_card.mp3');support.innerHTML='Slow — listen again.'},
   ()=>{support.innerHTML='<div style="display:flex;gap:30px"><div>Card → <b>This is my name card.</b></div><div>Name → <b>My name\'s ___.</b></div></div>';stage.innerHTML=''},
   ()=>{play('a_t_show_card.mp3');support.innerHTML='<b>This is my name card. My name\'s Noura.</b>'},
   ()=>{support.innerHTML='Say it with the frame:';stage.innerHTML='<span style="font-size:40px;font-weight:900">This is my ___ card.</span>'},
   ()=>{support.innerHTML='';stage.innerHTML=`<div class="namecard" style="width:230px;padding:14px"><div class="fl">${(stuName||'?')[0].toUpperCase()}</div><div class="nm" style="font-size:26px">${stuName||'___'}</div></div>`},
   ()=>tryAgain()],
  goodbye:[()=>{support.innerHTML=`<div><b>Good-bye. See you again.</b><span class="ar" style="display:block;font-size:19px;color:var(--blue)">مع السلامة — أراك لاحقاً</span></div>`;stage.innerHTML=charImg('omar',190)},
   ()=>{play('a_t_goodbye_slow.mp3');support.innerHTML='Slow — listen again.'},
   ()=>{support.innerHTML='<div style="display:flex;gap:30px"><div>START → <b>Hello!</b></div><div>END → <b>Good-bye!</b></div></div>';stage.innerHTML=''},
   ()=>{play('a_t_goodbye_seeyou.mp3');support.innerHTML='<b>Good-bye. See you again.</b>'},
   ()=>{support.innerHTML='Say it with the frame:';stage.innerHTML='<span style="font-size:44px;font-weight:900">Good-___. See you ___.</span>'},
   ()=>{support.innerHTML='';stage.innerHTML='<b style="font-size:26px">No text. Wave and say it.</b>'},
   ()=>tryAgain()]
 };
 function resetRemediate(){stepIdx=0;el.querySelectorAll('#fx-steps .step').forEach(b=>b.classList.remove('done'));el.querySelector('#c2-row').style.display='none';support.innerHTML=`<b style="font-size:26px">${SIX.find(s=>s.k===item).t}</b>`;stage.innerHTML=`<div style="transform:scale(1.8);opacity:.85">${icSVG(SIX.find(s=>s.k===item).icon)}</div>`;note.textContent='Start with Meaning.'}
 function tryAgain(){note.innerHTML='<b>Check 2 — Omar asks, no help at all.</b>';stage.innerHTML=`<div class="stage-col">${charImg('omar',200)}<div class="bubble qm">?</div></div>`;support.innerHTML='';const prompt={greet:'a_t_hello.mp3',askName:'a_t_whats_your_name.mp3',askStatus:'a_t_how_are_you.mp3',colorHunt:'a_t_find_color.mp3',nameCard:'a_t_show_card.mp3',goodbye:'a_t_goodbye_seeyou.mp3'}[item];setTimeout(()=>play(prompt),400);el.querySelector('#c2-row').style.display='flex'}
 el.querySelectorAll('#fx-pick [data-item]').forEach(b=>b.onclick=()=>{item=b.dataset.item;phase='remediate';resetRemediate()});
 el.querySelectorAll('#fx-steps .step').forEach(b=>b.onclick=()=>{const i=+b.dataset.step;if(i!==stepIdx||phase!=='remediate')return;b.classList.add('done');stepIdx++;note.textContent=['Meaning: 含义/短阿语提示','Slow: 慢速分段音频','Contrast: 混淆项对比','Model: 完整示范','Build: 句框支持','Hide help: 撤掉文字/阿语','Try again = Check 2'][i];ACT[item][i]()});
 el.querySelectorAll('#c2-row .grade').forEach(b=>b.onclick=()=>{results.check2[item]=b.dataset.g;results.show[item]={grade:b.dataset.g,errs:results.show[item]?.errs||[]};toast(`Check 2 · ${item}: ${b.dataset.g}`);el.querySelector('#c2-row').style.display='none'});
 /* Final Show */
 el.querySelector('#final-start').onclick=()=>{phase='final';fi=0;play('a_t_showtime.mp3');el.querySelector('#final-help').style.display='';el.querySelector('#final-grade').style.display='';el.querySelector('#fx-steps').style.display='none';note.innerHTML='<b>Final Show 进行中：</b>学生看图标连续展示 60–90 秒；每项 5 秒后 Help 才解锁，且只给首词；单点错误只标记不打断，Color Hunt 与姓名卡次序已调换。';finalRender()};
 function finalRender(){const k=FINAL_ORDER[fi];support.innerHTML='';stage.innerHTML=`<div class="stage-col"><div class="row" style="gap:14px">${FINAL_ORDER.map((kk,i)=>chipHTML(kk,i<fi?'done':i===fi?'on':'')).join('')}</div><div class="row" style="margin-top:16px;align-items:flex-end">${charImg('omar',170)}<div class="bubble qm">?</div></div></div>`;const helpBtn=el.querySelector('#final-help');helpBtn.style.opacity=.4;helpBtn.dataset.locked='1';clearTimeout(helpTimer);helpTimer=setTimeout(()=>{helpBtn.style.opacity=1;helpBtn.dataset.locked='0'},5000);note.innerHTML=`<b>Final Show · ${fi+1}/6 · ${SIX.find(s=>s.k===k).t}</b> — 等待学生开口，5 秒后才可 Help。`}
 el.querySelector('#final-help').onclick=()=>{if(phase!=='final')return;if(el.querySelector('#final-help').dataset.locked==='1'){toast('Wait 5 seconds');return}const s=SIX.find(x=>x.k===FINAL_ORDER[fi]);support.innerHTML=`<span style="font-size:26px">${s.hint.split(' ')[0]} …</span>`;results.show[s.k]=results.show[s.k]||{grade:null,errs:[]};if(!results.show[s.k].errs.includes('Needs script'))results.show[s.k].errs.push('Needs script')};
 el.querySelectorAll('#final-grade .grade').forEach(b=>b.onclick=()=>{if(phase!=='final')return;const k=FINAL_ORDER[fi];const prev=results.show[k];results.show[k]={grade:b.dataset.g,errs:prev?.errs||[]};dotsMark();fi++;if(fi<6)finalRender();else{el.querySelector('#final-help').style.display='none';el.querySelector('#final-grade').style.display='none';support.innerHTML='';stage.innerHTML=`<div class="stage-col"><b style="font-size:34px;color:var(--green)">Final Show complete!</b>${charImg('omar',150)}</div>`;sfx('sfx_success.mp3');note.textContent='Final Show 完成，去 S15。'}});
 function dotsMark(){}
 return{onEnter(){noAr();phase='pick';const f=failedItems();support.innerHTML=f.length?`<b style="font-size:24px">Fix ${f.length} item(s) from Check 1</b>`:'<b style="font-size:24px;color:var(--green)">Check 1 all A — go straight to Final Show</b>';stage.innerHTML='';el.querySelectorAll('#fx-pick [data-item]').forEach(b=>{b.style.outline=f.includes(b.dataset.item)?'3px solid var(--coral)':'none'})}}},{assessment:true});

/* S15 · 动态混合考试接口（问答 + 颜色或字母，先说后选） */
addScreen('School test style',`<div style="text-align:center;width:1000px"><span class="source-badge">SCHOOL TEST STYLE</span><h1 class="title sm" style="margin-top:12px">Listen. Say it. Then tap.</h1><div class="card copy" style="margin-top:16px;min-height:320px"><div class="row" id="ex-prompt" style="gap:16px"></div><div class="row" id="ex-opts" style="margin-top:18px;flex-wrap:wrap"></div><div class="dots" id="ex-dots">${'<span class="dot"></span>'.repeat(2)}</div></div></div><div class="teacher"><b>考试接口两题（与本课目标强关联）</b>：①What's your name? → 先说后选答句；②动态抽颜色或字母听辨（默认取 Check 1/Final Show 中较弱的一类）。真卷到位后按同结构替换题干。<div class="teacher-row"><span>Q2 type:</span><button class="error" data-q2="col">Color</button><button class="error" data-q2="ltr">Letter</button></div></div>`,el=>{
 let i=0,q2='col';const dots=[...el.querySelectorAll('#ex-dots .dot')];
 function weakType(){const cg=results.show.colorHunt?.grade,lg=null;return (cg&&cg!=='A')?'col':(Math.random()<.5?'col':'ltr')}
 function render(){const pr=el.querySelector('#ex-prompt'),op=el.querySelector('#ex-opts');let right='';
  if(i===0){pr.innerHTML=`<span class="source-badge" style="background:var(--sky);box-shadow:none;color:var(--blue)">Listen and choose</span><button class="speaker large" id="ex-play"></button><b style="font-size:24px">Say YOUR answer, then tap it</b>`;op.innerHTML=shuffle(["My name's ___.","I'm fine, thank you."]).map(t=>`<button class="phrase-opt" data-w="${t}">${t}</button>`).join('');right="My name's ___.";pr.querySelector('#ex-play').onclick=()=>play('a_t_whats_your_name.mp3');setTimeout(()=>play('a_t_whats_your_name.mp3'),600)}
  else if(q2==='col'){const c=shuffle(COLORS)[0];pr.innerHTML=`<span class="source-badge" style="background:var(--sky);box-shadow:none;color:var(--blue)">Listen and circle</span><button class="speaker large" id="ex-play"></button><b style="font-size:24px">Tap the color you hear</b>`;op.innerHTML=shuffle([c,...shuffle(COLORS.filter(x=>x.en!==c.en)).slice(0,2)]).map(swBtn).join('');right=c.en;pr.querySelector('#ex-play').onclick=()=>play(`a_t_${c.en}.mp3`);setTimeout(()=>play(`a_t_${c.en}.mp3`),600)}
  else{const L=shuffle(KEY8)[0];pr.innerHTML=`<span class="source-badge" style="background:var(--sky);box-shadow:none;color:var(--blue)">Listen and circle</span><button class="speaker large" id="ex-play"></button><b style="font-size:24px">Tap the letter you hear</b>`;op.innerHTML=shuffle([L,...shuffle(KEY8.filter(x=>x!==L)).slice(0,2)]).map(ltrBtn).join('');right=L;pr.querySelector('#ex-play').onclick=()=>play(`a_t_ltr_${L}.mp3`);setTimeout(()=>play(`a_t_ltr_${L}.mp3`),600)}
  let done=false;op.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>{if(done)return;done=true;if(b.dataset.w===right){b.classList.add('good');sfx('sfx_correct.mp3')}else{b.classList.add('bad');sfx('sfx_wrong.mp3')}dots[i]?.classList.add('done');i++;if(i<2)setTimeout(render,900);else setTimeout(()=>{pr.innerHTML='<b style="font-size:28px;color:var(--green)">Test style: done!</b>';op.innerHTML='';sfx('sfx_success.mp3')},900)})}
 el.querySelectorAll('[data-q2]').forEach(b=>b.onclick=()=>{q2=b.dataset.q2;if(i===1)render()});
 return{onEnter(){noAr();i=0;q2=weakType();dots.forEach(d=>d.classList.remove('done'));render()}}},{assessment:true});

/* S16 · Unit 1 六项能力墙 + My First Friend 徽章（真实结果，不写"全部掌握"） */
addScreen('My six powers · badge',`<div style="text-align:center"><span class="source-badge">UNIT 1 REPORT</span><h1 class="title sm" style="margin-top:12px">My First Friend badge</h1><div class="ability6" style="margin:22px auto 0">${SIX.map(s=>`<div class="card"><div class="ic">${icSVG(s.icon)}</div><strong>${s.t}</strong><p class="result-line" id="ab-${s.k}"><span class="g-badge g-none">–</span></p></div>`).join('')}</div><p class="subtitle" id="ab-sum" style="margin-top:16px"></p></div><div class="teacher"><b>六项核对，不看总分</b>：逐项回填 Check 1/Check 2/Final Show 定级（后测覆盖前测）。文案口径=独立 X/6 · 提示 Y/6 · 待练项列表——<b>禁止对家长说"全部掌握"</b>。截图发家长时六项徽章清晰可见。</div>`,el=>{return{onEnter(){noAr();play('a_t_new_friend.mp3');let ind=0,help=0,todo=[];SIX.forEach(s=>{const g=results.check2[s.k]||results.show[s.k]?.grade;el.querySelector('#ab-'+s.k).innerHTML=g?`<span class="g-badge g-${g}">${g}</span>`:'<span class="g-badge g-none">–</span>';if(g==='A')ind++;else if(g==='B')help++;else todo.push(s.t)});el.querySelector('#ab-sum').innerHTML=`Independent <b>${ind}/6</b> · With help <b>${help}/6</b>${todo.length?` · Keep practicing: <b>${todo.join(', ')}</b>`:''}${results.rushHits?`<br>Show Rush: ${results.rushHits} tasks in 60 seconds`:''}`}}},{assessment:true});

/* S17 · 家庭展示（自愿）+ Unit 1 复习 QR + 告别 */
addScreen('Home show · see you',`<div class="layout" style="grid-template-columns:1.15fr 1fr"><div><h1 class="title sm">Show your family!<br><span class="accent">If you want to.</span> <button class="speaker small" data-audio="a_t_home_show.mp3" style="vertical-align:middle"></button></h1><div class="card copy" style="margin-top:16px"><b style="font-size:24px">Your home show (voluntary)</b><p class="subtitle" style="font-size:19px">Meet someone at home: Hello! → What's your name? → How are you? → Find 3 colors → Show your name card → Good-bye!</p><p class="ar subtitle">اعرض ما تعلمته على أهلك إن أردت — ليس واجباً</p><div class="card" style="margin-top:12px;padding:16px;border-radius:18px;box-shadow:none;background:var(--sky)"><b>Workbook pp.63–70</b><p class="subtitle" style="font-size:18px">Finish the listen-and-color rows.</p></div></div></div><div class="card copy"><h2 style="font-size:34px">Home review</h2><div style="display:flex;align-items:center;gap:18px;margin-top:12px"><img src="${A}sec_qr_review.png" alt="home review QR" style="width:120px;height:120px;border-radius:14px"><a class="mini-pill blue" href="review/" style="display:inline-block;text-decoration:none">Open home review</a></div><p class="ar subtitle">امسح الرمز للمراجعة في البيت</p><div class="card" style="margin-top:14px;padding:16px;border-radius:18px;box-shadow:none;background:var(--sun)"><b>Say it</b><p class="subtitle" style="font-size:18px">Good-bye! See you again! <button class="speaker small" data-audio="a_t_goodbye_seeyou.mp3" style="vertical-align:middle"></button></p></div></div></div><div class="teacher"><b>收尾 60 秒</b>：家庭表演自愿、不作过关条件；扫 QR 进课后复习页（按本课弱项推送）。教师与学生互道 Good-bye 下课。结果截图发家长：六项徽章 + 待练项 + Rush 成绩。</div>`,null);

screens.forEach((s,i)=>{const b=document.createElement('button');b.textContent=`${i+1} · ${s.title}`;b.onclick=()=>{$('#thumbs').classList.remove('open');show(i)};$('#thumbs').appendChild(b)});
const q=new URLSearchParams(location.search),start=Math.max(0,Math.min(16,(Number(q.get('p')||q.get('page'))||1)-1));if(q.get('teacher')==='1'){document.body.classList.add('teacher-on');$('#btn-teacher').setAttribute('aria-pressed','true')}if(q.get('ar')==='1'&&start<12){document.body.classList.add('ar-on');$('#btn-ar').setAttribute('aria-pressed','true')}fit();show(start);
