/* We Can 1 · Global Lesson 3 · Unit 1 L2 · Hello, How Are You? */
const A='assets/';
const $=s=>document.querySelector(s);
let curAudio=null,curSfx=null,toastTimer=null;
const assessment={check1:null,check2:null,errors:new Set()};

function stopAudio(){if(curAudio){curAudio.pause();curAudio.currentTime=0;curAudio=null;}}
function play(src,onend){stopAudio();curAudio=new Audio(A+src);curAudio.play().catch(()=>{});if(onend)curAudio.addEventListener('ended',onend,{once:true});}
function playSlow(src,onend){stopAudio();curAudio=new Audio(A+src);curAudio.playbackRate=.78;curAudio.play().catch(()=>{});if(onend)curAudio.addEventListener('ended',onend,{once:true});}
function sfx(src){try{if(curSfx)curSfx.pause();curSfx=new Audio(A+src);curSfx.play().catch(()=>{});}catch(e){}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1600);}

const host=$('#screens'),screens=[];
const GUIDES=[
  '<b>Set up:</b> Check sound quickly. Keep this under one minute.',
  '<b>Lead-in:</b> Ask the learner’s name once. Then contrast arriving and leaving. Accept a point before asking for the word.',
  '<b>Outcome:</b> One real exchange from meeting to saying good-bye. Do not teach grammar terminology.',
  '<b>Input:</b> Point to the arriving friend. Model once, then learner asks you.',
  '<b>Input:</b> Require the whole response. If the learner says only “fine”, wait, then replay once.',
  '<b>Input:</b> Point back for “And you?” and use the walking-away scene for good-bye.',
  '<b>Function check:</b> Learner says the function before clicking. Three of four is enough to continue.',
  '<b>Hello Chant:</b> Play official CD1 05 once. Echo only the difficult line, then complete one natural exchange.',
  '<b>Relay:</b> Alternate roles. Fade the visible lines until the learner can carry the turn.',
  '<b>Good-bye Chant:</b> Play official CD1 07. Use a clear walking-away gesture.',
  '<b>Context practice:</b> Learner says the phrase before clicking the scene. Contrast arrival and departure.',
  '<b>Greeting Relay:</b> Listen, say the response, then tap. Speed is secondary to the correct function.',
  '<b>Check 1:</b> New character asks “How are you?” No Arabic or sentence frame. Learner answers and asks back.',
  '<b>Repair:</b> Meaning → Slow → Contrast → Model → Build → Hide help → Try again. Check 2 uses a new character.',
  '<b>School practice:</b> Learner answers aloud before choosing. Complete one listening-response item and one departure-situation item.',
  '<b>Record:</b> Set the level from Check 1/2 evidence, not page completion.',
  '<b>Exit:</b> Run the full meeting-to-good-bye exchange with gesture cues only. Then open the home review.'
];
function addScreen(objective,html,init){const el=document.createElement('section');el.className='screen';el.innerHTML=html;host.appendChild(el);const api=init?init(el):{};screens.push({objective,el,onEnter:api.onEnter,onLeave:api.onLeave});}
let cur=0;
function show(i){i=Math.max(0,Math.min(screens.length-1,i));if(screens[cur]?.onLeave)screens[cur].onLeave();stopAudio();cur=i;screens.forEach((s,k)=>s.el.classList.toggle('active',k===i));$('#objective').textContent=screens[i].objective;$('#teacher-copy').innerHTML=GUIDES[i]||'';$('#page-num').textContent=`${i+1} / ${screens.length}`;$('#progress').style.width=((i+1)/screens.length*100)+'%';$('#btn-prev').disabled=i===0;$('#btn-next').disabled=i===screens.length-1;document.querySelectorAll('#thumbs button').forEach((b,k)=>b.classList.toggle('cur',k===i));if(screens[i].onEnter)screens[i].onEnter();}
function fit(){const s=Math.min(innerWidth/1280,innerHeight/720);$('#stage').style.transform=`scale(${s})`;}
addEventListener('resize',fit);

$('#btn-ar').onclick=()=>{const on=document.body.classList.toggle('ar-on');$('#btn-ar').setAttribute('aria-pressed',on);};
$('#btn-teacher').onclick=()=>{const on=document.body.classList.toggle('teacher-on');$('#btn-teacher').setAttribute('aria-pressed',on);};
$('#btn-prev').onclick=()=>show(cur-1);$('#btn-next').onclick=()=>show(cur+1);$('#btn-thumbs').onclick=()=>$('#thumbs').classList.toggle('open');
$('#btn-fs').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>{});
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')show(cur+1);if(e.key==='ArrowLeft')show(cur-1);});
host.addEventListener('click',e=>{const b=e.target.closest('[data-audio]');if(b && !b.closest('#function-game')){play(b.dataset.audio);toast(b.dataset.toast||'Listen and say');}});

const speaker=(audio,small=false)=>`<button class="speaker${small?' small':''}" data-audio="${audio}"></button>`;
const pill=(text,color='#1670e8')=>`<span class="pill" style="background:${color};color:#fff;">${text}</span>`;
const scene=(src,alt)=>`<img class="pic" src="${A}${src}" alt="${alt}" style="width:100%;height:100%;object-fit:contain;background:#fffaf3;">`;
const sceneFocus=(src,alt)=>`<img class="pic" src="${A}${src}" alt="${alt}" style="width:100%;height:100%;object-fit:cover;object-position:right center;">`;

/* S1 */
addScreen('class setup',`<div style="direction:rtl;text-align:center;width:100%;"><h1 style="font-size:42px;color:#17324d;margin-bottom:24px;">قبل أن نبدأ الدرس</h1><div style="display:grid;grid-template-columns:1fr 1fr;gap:18px;max-width:900px;margin:auto;">${['افتح الميكروفون والكاميرا','تأكد أن الإنترنت يعمل جيدًا','اجلس في مكان هادئ','جهّز الكتاب والقلم'].map((t,i)=>`<div class="card" style="font-size:23px;font-weight:750;color:#324b68;padding:20px;">${String(i+1).padStart(2,'0')} · ${t}</div>`).join('')}</div><div style="margin-top:22px;">${speaker('a_t_soundcheck.mp3')}<div style="margin-top:8px;color:#8a6d3b;font-size:18px;">اضغط لاختبار الصوت</div></div></div>`);

/* S2 */
addScreen('Warm-up · Meet or leave?',`<div style="display:grid;grid-template-columns:1.15fr .85fr;gap:34px;width:100%;max-width:1160px;align-items:center;"><div style="height:440px;border-radius:28px;overflow:hidden;box-shadow:0 18px 40px rgba(23,50,77,.14);">${scene('sec_greeting_class.png','two friends greeting')}</div><div><span class="source-badge">ROLLING REVIEW</span><h1 style="font-size:40px;color:#17324d;margin:14px 0 8px;">Meet or leave?</h1><div class="card" style="margin-top:16px;"><div style="font-size:21px;color:#6e7b8b;">First, answer:</div><div style="display:flex;align-items:center;gap:14px;margin-top:10px;">${speaker('a_t_whats_your_name.mp3')}<b style="font-size:28px;color:#17324d;">What’s your name?</b></div></div><div style="display:flex;gap:12px;margin-top:18px;"><button class="pill scene-choice" data-ok="1" style="background:#24a66a;color:white;">Hello · meet</button><button class="pill scene-choice" data-ok="0" style="background:#eef3f7;color:#17324d;">Good-bye · leave</button></div><div class="ar" style="font-size:19px;color:#63758a;margin-top:12px;">لقاء أم وداع؟</div></div></div>`,el=>{el.querySelectorAll('.scene-choice').forEach(b=>b.onclick=()=>{if(b.dataset.ok==='1'){sfx('sfx_correct.mp3');toast('Yes — we meet and say Hello!');}else{sfx('sfx_wrong.mp3');toast('They are meeting. Try again.');}});return{};});

/* S3 */
addScreen('Today’s mission',`<div style="display:flex;gap:56px;align-items:center;justify-content:center;width:100%;"><div style="max-width:620px;"><span class="source-badge">WE CAN 1 · UNIT 1 · GOALS 03–04</span><h1 style="font-size:42px;color:#17324d;margin:15px 0 6px;">A whole greeting</h1><p style="font-size:20px;color:#6e7b8b;margin-bottom:18px;">Meet · ask · answer · ask back · say good-bye</p>${[["How are you?",'#1670e8'],["I’m fine, thank you. And you?",'#24a66a'],["Good-bye. See you again.",'#ff735c']].map(([t,c],i)=>`<div class="card" style="display:flex;align-items:center;gap:16px;padding:14px 18px;margin-bottom:12px;"><span style="width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:${c};color:white;font-weight:800;">${i+1}</span><b style="font-size:24px;color:#17324d;">${t}</b></div>`).join('')}</div><div style="width:270px;text-align:center;"><img src="${A}textbook_cover.png" style="width:250px;border-radius:12px;box-shadow:0 12px 28px rgba(23,50,77,.18);"><div style="font-size:18px;color:#1670e8;font-weight:800;margin-top:12px;">Student Book · pp.6–7</div></div></div>`);

function inputScreen(objective,img,badge,phrase,ar,audio,sub){addScreen(objective,`<div style="display:grid;grid-template-columns:1.1fr .9fr;gap:44px;width:100%;max-width:1120px;align-items:center;"><div style="height:430px;border-radius:28px;overflow:hidden;box-shadow:0 18px 42px rgba(23,50,77,.14);">${scene(img,phrase)}</div><div><span class="source-badge">${badge}</span><h1 style="font-size:50px;color:#17324d;line-height:1.12;margin:18px 0 10px;">${phrase}</h1><div class="ar" style="font-size:24px;color:#24a66a;font-weight:750;margin-bottom:16px;">${ar}</div><div style="display:flex;align-items:center;gap:16px;">${speaker(audio)}<span style="font-size:18px;color:#6e7b8b;">${sub}</span></div></div></div>`);}
inputScreen('Ask about feelings','sec_greeting_class.png','ASK','How are you?','كيف حالك؟','a_t_how_are_you.mp3','Look at your friend · ask');
inputScreen('Answer warmly','sec_char_wolf.png','ANSWER','I’m fine, thank you.','أنا بخير، شكرًا','a_t_fine_thank_you.mp3','Smile · answer the whole chunk');

/* S6 */
addScreen('Ask back · Say good-bye',`<div style="display:grid;grid-template-columns:1fr 1fr;gap:30px;width:100%;max-width:1120px;"><div class="card" style="display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;"><span class="source-badge">ASK BACK</span><h1 style="font-size:48px;color:#17324d;margin:20px 0 14px;">And you?</h1>${speaker('a_t_and_you.mp3')}<div class="ar" style="font-size:21px;color:#24a66a;margin-top:12px;">وأنت؟</div></div><div style="height:430px;position:relative;border-radius:28px;overflow:hidden;box-shadow:0 16px 38px rgba(23,50,77,.14);">${sceneFocus('sec_goodbye_class.png','friends saying goodbye')}<div style="position:absolute;left:22px;top:22px;display:flex;flex-direction:column;gap:10px;"><button class="pill" data-audio="a_t_goodbye.mp3" style="background:#ff735c;color:white;font-size:20px;">Good-bye.</button><button class="pill" data-audio="a_t_see_you_again.mp3" style="background:#17324d;color:white;font-size:20px;">See you again.</button></div></div></div>`);

/* S7 */
addScreen('Listen for function',`<div id="function-game" style="width:1120px;"><div style="display:flex;justify-content:center;gap:18px;margin-bottom:24px;"><div class="card" id="fn-round" style="padding:10px 20px;font-weight:800;color:#ff735c;">1 / 4</div>${speaker('a_t_how_are_you.mp3')}</div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:18px;">${[['Ask how','?','#1670e8'],['Answer','✓','#24a66a'],['Ask back','↩','#ffc84a'],['Leave','→','#ff735c']].map(([t,ic,c],i)=>`<button class="card fn-card" data-k="${i}" style="height:260px;border:0;cursor:pointer;color:#17324d;"><div style="width:86px;height:86px;border-radius:50%;display:grid;place-items:center;margin:auto;background:${c};color:white;font-size:44px;font-weight:900;">${ic}</div><div style="font-size:24px;font-weight:800;margin-top:20px;">${t}</div></button>`).join('')}</div></div>`,el=>{const rounds=[['a_t_how_are_you.mp3',0],['a_t_fine_thank_you.mp3',1],['a_t_and_you.mp3',2],['a_t_goodbye.mp3',3]];let n=0;const playRound=()=>{el.querySelector('#fn-round').textContent=`${n+1} / 4`;play(rounds[n][0]);};el.querySelector('.speaker').onclick=playRound;el.querySelectorAll('.fn-card').forEach(b=>b.onclick=()=>{if(+b.dataset.k===rounds[n][1]){sfx('sfx_correct.mp3');toast('Correct function!');n++;if(n===4){n=0;sfx('sfx_success.mp3');toast('Four functions complete!');}setTimeout(playRound,500);}else{sfx('sfx_wrong.mp3');toast('Listen to the meaning again.');playRound();}});return{onEnter(){n=0;setTimeout(playRound,300);}};});

/* S8 */
addScreen('Official Hello Chant',`<div style="display:grid;grid-template-columns:1.05fr .95fr;gap:38px;width:100%;max-width:1120px;align-items:center;"><div style="height:430px;border-radius:28px;overflow:hidden;">${scene('sec_greeting_relay.png','greeting relay')}</div><div><span class="source-badge">STUDENT BOOK p.6 · CD1 05</span><h1 style="font-size:38px;color:#17324d;margin:14px 0 18px;">Hello Chant</h1><div class="card" style="font-size:28px;line-height:1.65;color:#17324d;"><b style="color:#1670e8;">Hello, hello, hello.</b><br>How are you?<br><b style="color:#24a66a;">I’m fine. I’m fine.</b><br>I’m fine, thank you. And you?</div><button class="pill" data-audio="a_official_cd1_05_06.mp3" style="margin-top:18px;background:#1670e8;color:white;font-size:18px;">Play official track</button></div></div>`);

/* S9 */
addScreen('Chant relay',`<div style="width:100%;max-width:1080px;text-align:center;"><span class="source-badge">TEACHER ↔ LEARNER</span><h1 style="font-size:38px;color:#17324d;margin:14px 0 22px;">Pass the greeting</h1><div id="relay-lines" style="display:grid;grid-template-columns:1fr 1fr;gap:16px;">${[['Hello! How are you?','a_t_check_prompt.mp3','#1670e8'],['I’m fine, thank you.','a_t_fine_thank_you.mp3','#24a66a'],['And you?','a_t_and_you.mp3','#ffc84a'],['I’m fine.','a_t_im_fine.mp3','#ff735c']].map(([t,a,c],i)=>`<button class="card relay-line" data-audio="${a}" data-k="${i}" style="border:3px solid ${c};cursor:pointer;font-size:28px;font-weight:800;color:#17324d;min-height:105px;">${t}</button>`).join('')}</div><button id="relay-hide" class="pill" style="margin-top:20px;background:#17324d;color:white;">Hide one line</button></div>`,el=>{let hidden=0;el.querySelector('#relay-hide').onclick=()=>{const cards=[...el.querySelectorAll('.relay-line')];if(hidden<4){cards[hidden].style.color='transparent';cards[hidden].style.background='#eef3f7';hidden++;toast('Say the hidden line.');}else{cards.forEach(c=>{c.style.color='#17324d';c.style.background='#fff';});hidden=0;}};return{onEnter(){hidden=0;el.querySelectorAll('.relay-line').forEach(c=>{c.style.color='#17324d';c.style.background='#fff';});}};});

/* S10 */
addScreen('Official Good-bye Chant',`<div style="display:grid;grid-template-columns:1.08fr .92fr;gap:38px;width:100%;max-width:1120px;align-items:center;"><div style="height:430px;border-radius:28px;overflow:hidden;">${sceneFocus('sec_goodbye_class.png','friends leaving')}</div><div><span class="source-badge">STUDENT BOOK p.6 · CD1 07</span><h1 style="font-size:38px;color:#17324d;margin:14px 0 18px;">Good-bye Chant</h1><div class="card" style="font-size:30px;line-height:1.65;color:#17324d;"><b style="color:#ff735c;">Good-bye, good-bye.</b><br>Good-bye to you.<br><b style="color:#1670e8;">Oh, see you again.</b></div><button class="pill" data-audio="a_official_cd1_07_08.mp3" style="margin-top:18px;background:#ff735c;color:white;font-size:18px;">Play official track</button></div></div>`);

/* S11 */
addScreen('Choose the moment',`<div style="width:100%;max-width:1100px;text-align:center;"><h1 style="font-size:38px;color:#17324d;margin-bottom:22px;">Arriving or leaving?</h1><div style="display:grid;grid-template-columns:1fr 1fr;gap:28px;"><button class="moment card" data-k="meet" style="height:390px;border:0;cursor:pointer;padding:0;overflow:hidden;position:relative;">${scene('sec_greeting_class.png','arriving')}<span class="pill" style="position:absolute;left:18px;bottom:18px;background:#24a66a;color:white;font-size:19px;">Arriving</span></button><button class="moment card" data-k="leave" style="height:390px;border:0;cursor:pointer;padding:0;overflow:hidden;position:relative;">${sceneFocus('sec_goodbye_class.png','leaving')}<span class="pill" style="position:absolute;left:18px;bottom:18px;background:#ff735c;color:white;font-size:19px;">Leaving</span></button></div><div style="display:flex;justify-content:center;gap:14px;margin-top:18px;"><button class="pill moment-prompt" data-target="meet" data-audio="a_t_how_are_you.mp3" style="background:#1670e8;color:white;">Hear a phrase</button><button class="pill moment-prompt" data-target="leave" data-audio="a_t_goodbye.mp3" style="background:#17324d;color:white;">Next phrase</button></div></div>`,el=>{let target='meet';el.querySelectorAll('.moment-prompt').forEach(b=>b.onclick=()=>{target=b.dataset.target;});el.querySelectorAll('.moment').forEach(b=>b.onclick=()=>{if(b.dataset.k===target){sfx('sfx_correct.mp3');toast('Right moment!');}else{sfx('sfx_wrong.mp3');toast('Look: are they arriving or leaving?');}});return{};});

/* S12 */
addScreen('60-second Greeting Relay',`<div id="speed-game" style="width:1160px;height:500px;border-radius:30px;background:linear-gradient(135deg,#eaf4ff,#fff7e8);position:relative;padding:28px 34px;"><div style="display:flex;justify-content:center;gap:18px;"><div class="card" id="sp-score" style="padding:9px 18px;font-weight:800;">Score: 0</div><div class="card" id="sp-time" style="padding:9px 18px;font-weight:800;color:#ff735c;">60s</div></div><div id="sp-prompt" style="text-align:center;font-size:34px;font-weight:850;color:#17324d;margin:30px 0 22px;">Listen. Say it. Tap.</div><div id="sp-options" style="display:grid;grid-template-columns:repeat(3,1fr);gap:20px;"></div><div id="sp-start" style="position:absolute;inset:0;background:#ffffffdf;border-radius:30px;display:flex;flex-direction:column;align-items:center;justify-content:center;"><h1 style="font-size:42px;color:#17324d;">Greeting Relay</h1><p style="font-size:21px;color:#6e7b8b;margin:10px 0 20px;">Listen · say the answer · tap</p><button class="navbtn" id="sp-go">Start</button></div></div>`,el=>{const items=[{a:'a_t_how_are_you.mp3',ans:'I’m fine, thank you.',opts:['I’m fine, thank you.','My name’s Ali.','Good-bye.']},{a:'a_t_fine_thank_you.mp3',ans:'And you?',opts:['How are you?','And you?','See you again.']},{a:'a_t_goodbye.mp3',ans:'See you again.',opts:['Hello!','I’m fine.','See you again.']}];let score=0,left=60,timer=null,running=false,current=null;function next(){current=items[Math.floor(Math.random()*items.length)];play(current.a);el.querySelector('#sp-options').innerHTML=[...current.opts].sort(()=>Math.random()-.5).map(t=>`<button class="card sp-opt" data-v="${t}" style="height:180px;border:0;cursor:pointer;font-size:24px;font-weight:800;color:#17324d;">${t}</button>`).join('');el.querySelectorAll('.sp-opt').forEach(b=>b.onclick=()=>{if(!running)return;if(b.dataset.v===current.ans){score+=10;sfx('sfx_correct.mp3');el.querySelector('#sp-score').textContent='Score: '+score;toast('Correct — say it!');next();}else{sfx('sfx_wrong.mp3');toast('Listen to the function again.');play(current.a);}});}el.querySelector('#sp-go').onclick=()=>{el.querySelector('#sp-start').style.display='none';score=0;left=60;running=true;el.querySelector('#sp-score').textContent='Score: 0';next();timer=setInterval(()=>{left--;el.querySelector('#sp-time').textContent=left+'s';if(left<=0){clearInterval(timer);running=false;sfx('sfx_success.mp3');el.querySelector('#sp-start').style.display='flex';el.querySelector('#sp-start').innerHTML=`<h1 style="font-size:42px;color:#17324d;">Time!</h1><p style="font-size:26px;color:#ff735c;margin:12px;">Score: ${score}</p><button class="navbtn" onclick="location.reload()">Play again</button>`;}},1000);};return{onEnter(){if(new URLSearchParams(location.search).get('play'))setTimeout(()=>el.querySelector('#sp-go').click(),200);},onLeave(){clearInterval(timer);running=false;}};});

/* S13 */
addScreen('Check 1 · Real greeting',`<div style="display:grid;grid-template-columns:430px 1fr;gap:54px;align-items:center;width:100%;max-width:1080px;"><div class="card" style="height:430px;display:grid;place-items:center;"><img src="${A}sec_char_wolf.png" style="width:330px;height:360px;object-fit:contain;"></div><div><span class="source-badge">CHECK 1 · NO HELP</span><h1 style="font-size:42px;color:#17324d;margin:16px 0 8px;">How are you?</h1><p style="font-size:22px;color:#6e7b8b;line-height:1.5;">Answer. Then ask back.</p><div style="display:flex;align-items:center;gap:18px;margin-top:26px;">${speaker('a_t_check_prompt.mp3')}<div class="card" style="font-size:20px;font-weight:800;color:#17324d;">1 · Listen &nbsp; 2 · Answer &nbsp; 3 · Ask back</div></div></div></div><div class="teacher-only" style="position:absolute;left:36px;right:36px;bottom:14px;gap:7px;justify-content:center;align-items:center;"><span class="pill" style="background:#17324d;color:white;">Error:</span>${[['name','Answers with name'],['fine','Only “fine”'],['thanks','Misses “thank you”'],['and','Misses “And you?”']].map(([k,t])=>`<button class="pill error-tag" data-error="${k}">${t}</button>`).join('')}<button class="pill rate-tag green" data-rate="A">A</button><button class="pill rate-tag" data-rate="B" style="background:#ffc84a;color:#17324d;">B</button><button class="pill rate-tag coral" data-rate="C">C</button></div>`,el=>{el.querySelectorAll('.error-tag').forEach(b=>b.onclick=()=>{assessment.errors.add(b.dataset.error);b.style.background='#ffc84a';});el.querySelectorAll('.rate-tag').forEach(b=>b.onclick=()=>{assessment.check1=b.dataset.rate;toast('Check 1: '+b.dataset.rate);});return{onEnter(){assessment.check1=null;assessment.check2=null;assessment.errors.clear();el.querySelectorAll('.error-tag').forEach(b=>b.style.background='');}};});

/* S14 */
addScreen('Repair · Check 2',`<div style="display:grid;grid-template-columns:400px 1fr;gap:46px;align-items:center;width:100%;max-width:1080px;"><div class="card" style="height:410px;display:grid;place-items:center;"><img src="${A}sec_char_cat.png" style="width:315px;height:350px;object-fit:contain;"></div><div><span class="source-badge">HELP FADES → CHECK 2</span><h1 style="font-size:40px;color:#17324d;margin:14px 0 12px;">Try with a new friend</h1><div id="repair-view" class="card" style="min-height:175px;display:flex;align-items:center;justify-content:center;text-align:center;font-size:27px;font-weight:800;color:#17324d;">${speaker('a_t_new_place_prompt.mp3')}</div></div></div><div class="teacher-only" style="position:absolute;left:24px;right:24px;bottom:10px;gap:6px;justify-content:center;align-items:center;flex-wrap:wrap;">${['Meaning','Slow','Contrast','Model','Build','Hide help','Try again'].map((t,i)=>`<button class="pill repair-step" data-step="${i}" style="background:#eaf4ff;color:#1670e8;">${i+1}. ${t}</button>`).join('')}<button class="pill check2 green" data-rate="A">A</button><button class="pill check2" data-rate="B" style="background:#ffc84a;color:#17324d;">B</button><button class="pill check2 coral" data-rate="C">C</button></div>`,el=>{const view=el.querySelector('#repair-view');let nextStep=0;const steps=[()=>view.innerHTML='<div><div style="font-size:48px;">☺ → ?</div><div class="ar" style="display:block;color:#24a66a;">كيف حالك؟</div></div>',()=>{view.innerHTML='<div>Listen slowly. Keep every word.</div>';playSlow('a_t_fine_thank_you_slow.mp3');},()=>view.innerHTML='<div style="display:flex;gap:12px;"><span class="pill blue">name</span><span style="font-size:36px;">≠</span><span class="pill green">feeling</span></div>',()=>{view.innerHTML='<div>How are you?<br><span style="color:#24a66a;">I’m fine, thank you. And you?</span></div>';play('a_t_full_exchange.mp3');},()=>view.innerHTML='<div style="display:flex;gap:10px;flex-wrap:wrap;justify-content:center;">'+['I’m','fine,','thank you.','And you?'].map(x=>`<span class="pill blue">${x}</span>`).join('')+'</div>',()=>view.innerHTML='<div style="font-size:22px;color:#6e7b8b;">No words now. Look at the new friend.</div>',()=>{view.innerHTML='<button class="speaker" data-audio="a_t_new_place_prompt.mp3"></button>';play('a_t_new_place_prompt.mp3');toast('Check 2 — answer and ask back.');}];el.querySelectorAll('.repair-step').forEach(b=>b.onclick=()=>{const i=+b.dataset.step;if(i>nextStep){toast('Use the next step.');return;}steps[i]();b.style.background='#24a66a';b.style.color='white';if(i===nextStep)nextStep=Math.min(6,nextStep+1);});el.querySelectorAll('.check2').forEach(b=>b.onclick=()=>{assessment.check2=b.dataset.rate;toast('Check 2: '+b.dataset.rate);});return{onEnter(){nextStep=0;view.innerHTML='<button class="speaker" data-audio="a_t_new_place_prompt.mp3"></button>';el.querySelectorAll('.repair-step').forEach(b=>{b.style.background='#eaf4ff';b.style.color='#1670e8';});}};});

/* S15 */
addScreen('School practice',`<div style="display:grid;grid-template-columns:1fr 1fr;gap:34px;width:100%;max-width:1120px;"><div class="card"><h2 style="font-size:25px;color:#17324d;text-align:center;">1 · Listen and choose</h2><div style="text-align:center;margin:18px;">${speaker('a_t_how_are_you.mp3')}</div><div id="exam-answer">${['My name’s Ali.','I’m fine, thank you.'].map((t,i)=>`<button class="exam-opt card" data-ok="${i}" style="width:100%;border:0;margin-bottom:12px;font-size:22px;font-weight:800;cursor:pointer;color:#17324d;">${t}</button>`).join('')}</div></div><div class="card"><h2 style="font-size:25px;color:#17324d;text-align:center;">2 · Choose the scene</h2><p style="text-align:center;color:#6e7b8b;margin:10px 0 16px;">What do you say when you leave?</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;"><button class="exam-scene" data-ok="0" style="height:250px;border:0;border-radius:20px;overflow:hidden;cursor:pointer;">${scene('sec_greeting_class.png','arriving')}</button><button class="exam-scene" data-ok="1" style="height:250px;border:0;border-radius:20px;overflow:hidden;cursor:pointer;">${sceneFocus('sec_goodbye_class.png','leaving')}</button></div></div></div>`,el=>{el.querySelectorAll('.exam-opt,.exam-scene').forEach(b=>b.onclick=()=>{if(b.dataset.ok==='1'){sfx('sfx_correct.mp3');b.style.outline='4px solid #24a66a';toast('Correct!');}else{sfx('sfx_wrong.mp3');toast('Try again.');}});return{};});

/* S16 */
addScreen('Greeting Star',`<div style="text-align:center;width:100%;"><span class="source-badge">TODAY’S EVIDENCE</span><h1 style="font-size:44px;color:#17324d;margin:14px 0 24px;">I can greet a friend</h1><div style="display:flex;gap:26px;justify-content:center;">${[['Ask how','#1670e8'],['Answer + ask back','#24a66a'],['Say good-bye','#ff735c']].map(([t,c])=>`<div class="card" style="width:300px;border:3px solid ${c};padding:28px 18px;"><div style="width:74px;height:74px;border-radius:50%;display:grid;place-items:center;margin:auto;background:${c};color:white;font-size:38px;font-weight:900;">✓</div><div style="font-size:23px;font-weight:800;color:#17324d;margin-top:14px;">${t}</div></div>`).join('')}</div><div id="ability-level" class="card" style="display:inline-flex;margin-top:22px;padding:10px 22px;font-size:19px;font-weight:800;color:#17324d;">Level: not recorded</div></div>`,el=>({onEnter(){const level=assessment.check2||assessment.check1||'Not recorded';const copy={A:'A · Independent',B:'B · With help, then independent',C:'C · Keep practising','Not recorded':'Not recorded'}[level];el.querySelector('#ability-level').textContent='Level: '+copy;if(level!=='Not recorded')setTimeout(()=>play('a_t_great_job.mp3'),200);}}));

/* S17 */
addScreen('Exit task · Home review',`<div style="display:grid;grid-template-columns:1.08fr .92fr;gap:32px;width:100%;max-width:1120px;"><div class="card" style="padding:24px;text-align:center;"><h2 style="font-size:30px;color:#17324d;">One whole greeting</h2><div style="height:280px;border-radius:22px;overflow:hidden;margin:14px 0;">${scene('sec_greeting_class.png','real greeting')}</div><div id="exit-flow" style="display:flex;justify-content:center;gap:12px;align-items:center;"><span class="pill blue">Meet</span><span style="font-size:24px;">→</span><span class="pill green">Ask</span><span style="font-size:24px;">→</span><span class="pill coral">Leave</span></div><button id="exit-help" class="pill" style="margin-top:15px;background:#eef6ff;color:#1670e8;">Help · first words only</button></div><div class="card" style="padding:26px;text-align:center;"><h2 style="font-size:30px;color:#17324d;">Home review</h2><p style="font-size:22px;color:#8a6d3b;margin:14px 0;">Workbook · pp.65–66</p><div style="display:flex;flex-direction:column;gap:12px;text-align:left;max-width:360px;margin:20px auto;">${[['1','Trace I’m / fine / thank you'],['2','Listen and choose the reply'],['3','Say the whole greeting']].map(([n,t])=>`<div style="display:flex;align-items:center;gap:12px;"><span style="width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#1670e8;color:white;font-weight:800;">${n}</span><b style="font-size:18px;color:#17324d;">${t}</b></div>`).join('')}</div><a href="review/" class="pill" style="background:#24a66a;color:white;text-decoration:none;font-size:18px;margin-top:10px;">Open home review</a><div class="ar" style="font-size:17px;color:#63758a;margin-top:12px;">راجع الدرس في البيت</div></div></div>`,el=>{el.querySelector('#exit-help').onclick=()=>{el.querySelector('#exit-flow').innerHTML=`${pill('Hello…','#1670e8')}<span style="font-size:24px;">→</span>${pill('How…','#24a66a')}<span style="font-size:24px;">→</span>${pill('Good…','#ff735c')}`;toast('First words only. Finish the talk.');};return{onEnter(){el.querySelector('#exit-flow').innerHTML='<span class="pill blue">Meet</span><span style="font-size:24px;">→</span><span class="pill green">Ask</span><span style="font-size:24px;">→</span><span class="pill coral">Leave</span>';}};});

screens.forEach((s,k)=>{const b=document.createElement('button');b.textContent=`${k+1} · ${s.objective.slice(0,10)}`;b.onclick=()=>{$('#thumbs').classList.remove('open');show(k);};$('#thumbs').appendChild(b);});
document.addEventListener('click',e=>{
  const again=e.target.closest('#sp-start .navbtn');
  if(again && again.textContent.trim()==='Play again'){
    e.preventDefault();e.stopImmediatePropagation();
    location.href=location.pathname+'?p=12';
  }
},true);
host.addEventListener('click',e=>{
  const firstRepair=e.target.closest('.repair-step[data-step="0"]');
  if(firstRepair)setTimeout(()=>{
    const view=$('#repair-view');
    if(view)view.innerHTML='<div><div style="font-size:22px;letter-spacing:1px;color:#1670e8;">FEELING → ?</div><div class="ar" style="display:block;color:#24a66a;margin-top:10px;">كيف حالك؟</div></div>';
  },0);
  if(!e.target.closest('.check2'))return;
  setTimeout(()=>{
    const view=$('#repair-view');
    if(view)view.innerHTML='<div><div style="font-size:20px;color:#6e7b8b;margin-bottom:8px;">One whole talk</div><div style="display:flex;gap:10px;justify-content:center;align-items:center;"><span class="pill blue">Meet</span><span>→</span><span class="pill green">Ask</span><span>→</span><span class="pill coral">Leave</span></div><button class="pill" data-audio="a_t_full_exchange.mp3" style="margin-top:14px;background:#17324d;color:white;">Hear the whole talk</button></div>';
  },0);
});
const query=new URLSearchParams(location.search);const p0=parseInt(query.get('p')||'1',10);if(query.get('ar')){document.body.classList.add('ar-on');$('#btn-ar').setAttribute('aria-pressed','true');}if(query.get('teacher')){document.body.classList.add('teacher-on');$('#btn-teacher').setAttribute('aria-pressed','true');}fit();show(isNaN(p0)?0:p0-1);
